### ISSUE TITLE
Add feature to make complex type nullable

### ISSUE THREAD

**Issue by chaitanya-mahamuni** [strongloop/strong-soap#103]
I want to set "xsi:nil=true" for complex type.
I was checking code in [xmlHandler.js](https://github.com/strongloop/strong-soap/blob/master/src/parser/xmlHandler.js)
From [line number 120](https://github.com/strongloop/strong-soap/blob/master/src/parser/xmlHandler.js#L120), only Simple types are considered for adding  "xsi:nil=true" attribute.
If I add below code above [line number 120](https://github.com/strongloop/strong-soap/blob/master/src/parser/xmlHandler.js#L120), then it adds "xsi:nil=true" attribute to any node having value 'null' without checking whether it is simple or not
    `if (val == null) {
            if (descriptor.isNillable) {
                // Set xsi:nil = true
                declareNamespace(nsContext, element, 'xsi', helper.namespaces.xsi);
                element.attribute('xsi:nil', true);
            }
        }`
Is this change will affect anywhere in library?

**Comment by rashmihunt** [comment]
chaitanya-mahamuni  to understand the schema of your usecase can you attach your wsdl and XSD where you have declared nillable="true" ?

**Comment by rashmihunt** [comment]
- [ ]  Add xsi:nil=true to complexType 
- [ ] Add mocha test 
- [ ] Make sure no regression in existing tests/code

**Comment by rashmihunt** [comment]
PR - https://github.com/strongloop/strong-soap/pull/106

**Comment by rashmihunt** [comment]
Fixed in latest npm version 1.2.5

**Comment by chaitanya-mahamuni** [comment]
@rashmihunt : great work... updated to 1.2.5.. Thanks for resolving issue... :)

**Comment by sieteunoseis** [comment]
Not getting isNillable: false for any elements. For example:

    <xsd:complexType name="XSipProfile">
        <xsd:sequence minOccurs="0">
            <xsd:element maxOccurs="1" minOccurs="1" name="name" nillable="false" type="axlapi:String50"/>
         </xsd:sequence>
    </xsd:complexType>
