### ISSUE TITLE
Slow executuion when creating client

### ISSUE THREAD

**Issue by castleofbones** [strongloop/strong-soap#105]
Hi,

I'm currenlty working on integration with Experian's Quick Address OnDemand service and have hit an issue.

I am able to generate the necessary XML to make a call to their service, however, I am seeing very slow execution times when creating the client with 15-20 seconds delay being introduced.  Yet if I copy the request XML into Postman and execute the call returns in ~60ms.

I'm using the following to create my client:

```
_createClient(callback) {
        const soap = require('strong-soap').soap;
        const options = {
            envelopeKey: 'soap12',
            forceSoapVersion: '1.2'
        }
        soap.createClient(__dirname + '/ProOnDemandService.xml', options, (err, client) => {
            if (err) {
                callback(err);
            }
            console.log('SOAP client created');
            client.on('request', (req) => {
                console.log(req);
            })
            callback(null, client);
        }, this.endPoint);
    }

```
The generated XML for the request is:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope">
  <soap12:Header>
    <QAQueryHeader xmlns="http://www.qas.com/OnDemand-2011-03">
      <QAAuthentication>
        <Username>xxxxxxxx</Username>
        <Password>xxxxxxxx</Password>
      </QAAuthentication>
      <Security>xml</Security>
    </QAQueryHeader>
  </soap12:Header>
  <soap12:Body>
    <ns1:QACanSearch xmlns:ns1="http://www.qas.com/OnDemand-2011-03" Locatistaion="" RequestTag="">
      <ns1:Country>GBR</ns1:Country>
      <ns1:Engine Flatten="true" Intensity="Exact" PromptSet="Default"/>
      <ns1:Layout>FullPAF</ns1:Layout>
    </ns1:QACanSearch>
  </soap12:Body>
</soap12:Envelope>

```

When piping the debug output to I file I can see the point in the execution that the delay is happening:

```
Thu, 08 Jun 2017 07:56:08 GMT strong-soap:wsdl wsdl open. request_headers: undefined request_options: undefined
Thu, 08 Jun 2017 07:56:08 GMT strong-soap:http Http request: {"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"www.w3.org","port":null,"hostname":"www.w3.org","hash":null,"search":null,"query":null,"pathname":"/TR/xmldsig-core/xmldsig-core-schema.xsd","path":"/TR/xmldsig-core/xmldsig-core-schema.xsd","href":"http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd"},"method":"GET","headers":{"User-Agent":"strong-soap/1.2.3","Accept":"text/html,application/xhtml+xml,application/xml,text/xml;q=0.9,*/*;q=0.8","Accept-Encoding":"none","Accept-Charset":"utf-8","Connection":"close","Host":"www.w3.org"},"followAllRedirects":true,"body":null}
Thu, 08 Jun 2017 07:56:24 GMT strong-soap:http Http response body: "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!DOCTYPE schema\n  PUBLIC \"-//W3C//DTD XMLSchema 200102//EN\" \"http://www.w3.org/2001/XMLSchema.dtd\"\n [\n   <!ATTLIST schema \n     xmlns:ds CDATA #FIXED \"http://www.w3.org/2000/09/xmldsig#\">\n   <!ENTITY dsig 'http://www.w3.org/2000/09/xmldsig#'>\n   

... TRUNCATED TO SAVE SPACE ...

<element name=\"Exponent\" type=\"ds:CryptoBinary\"/> \n  </sequence>\n</complexType> \n\n<!-- End KeyValue Element-types -->\n\n<!-- End Signature -->\n\n</schema>\n"
Thu, 08 Jun 2017 07:56:24 GMT strong-soap:wsdl WSDL xml: <?xml version="1.0" encoding="utf-8"?>
```
Any help in over-comming this issue is much appreciated.

Cheers

Darren

**Comment by rashmihunt** [comment]
@castleofbones 
- Are you running strong-soap with debug enabled? If yes, this will cause the performance issues.
- I also noticed you have console.log statements in your client code above, which will cause performance issues as well. Can you remove them and check?

**Comment by castleofbones** [comment]
Hi,

I'm not always running it in debug that was merely to get some insight into where the slow down is occurring.

Same thing with the console.log statements, obviously not for production but helpful when to get the xml.

The debug shows a request taking 16 seconds to w3.org that is firing whenever I create  client.  How do I prevent this from happening?

**Comment by castleofbones** [comment]
I've just tried running the request without the `options` variable to force SOAP 1.2 and the call works perfectly, go figure :-/

Guess I'll stick with that for now but any thoughts around the SOAP 1.2 would still be appreciated.

**Comment by rashmihunt** [comment]
@castleofbones Are you pointing out options variable to force SOAP 1.2 was causing performance issue or is SOAP 1.2 is a different issue than the performance?

**Comment by rashmihunt** [comment]
@castleofbones I am bit confused by "I've just tried running the request without the options variable to force SOAP 1.2 and the call works perfectly" Does this mean your original performance issue no longer exist?

**Comment by kaaljabr** [comment]
@castleofbones did you solve this issue? I am running into exactly the same issue with Experian and createClient function.
