### ISSUE TITLE
TypeError on result

### ISSUE THREAD

**Issue by alewaros** [strongloop/strong-soap#108]
With the following code I'm getting a TypeError inside of the library.

```javascript
const {soap} = require('strong-soap')
const url =
  'https://cmtpi.siteminder.com/siteconnect/services/siteconnect_v1.1.0.wsdl'

soap.createClient(url, {}, (error, client) => {
  console.log(error, client)
})
```

Error
```
          t.postProcess(definitions);
           ^

TypeError: Cannot read property 'postProcess' of null
    at /Users/aj/Developer/Selina/Selina-Booking-API/node_modules/strong-soap/src/parser/xsd/simpleType.js:48:12
    at Array.forEach (native)
    at SimpleType.postProcess (/Users/aj/Developer/Selina/Selina-Booking-API/node_modules/strong-soap/src/parser/xsd/simpleType.js:47:32)
    at visitDfs (/Users/aj/Developer/Selina/Selina-Booking-API/node_modules/strong-soap/src/parser/xsd/schema.js:83:10)
    at /Users/aj/Developer/Selina/Selina-Booking-API/node_modules/strong-soap/src/parser/xsd/schema.js:87:7
    at Array.forEach (native)
    at visitDfs (/Users/aj/Developer/Selina/Selina-Booking-API/node_modules/strong-soap/src/parser/xsd/schema.js:86:19)
    at /Users/aj/Developer/Selina/Selina-Booking-API/node_modules/strong-soap/src/parser/xsd/schema.js:87:7
    at Array.forEach (native)
    at visitDfs (/Users/aj/Developer/Selina/Selina-Booking-API/node_modules/strong-soap/src/parser/xsd/schema.js:86:19)
```

**Comment by rashmihunt** [comment]
@alewaros can you paste the snippet your WSDL or XSD where 'union' element is defined? It should look something like 
```
  <xs:simpleType name="xxx">
    <xs:union memberTypes="yyy">
    ...
```

I am guessing by the error no 'memberTypes' is defined in your case.

**Comment by rashmihunt** [comment]
@alewaros I can access the XSDs myself using your WSDL URL.. looking into it further which memberTypes is not defined.

**Comment by alewaros** [comment]
The WSDL URL belongs to a company named Siteminder. What kind of problem presents the fact that the memberTypes property is not defined?

Is it something that they have to fix?

**Comment by rashmihunt** [comment]
@alewaros looking at https://cmtpi.siteminder.com/siteconnect/schema/OTA_AirCommonTypes.xsd
the failure is for ```<xs:simpleType>
<xs:union memberTypes="UpperCaseAlphaLength1to3 OTA_CodeType"/>
</xs:simpleType>```  
The memberTypes UpperCaseAlphaLength1to3 and OTA_CodeType are not defined in the XSD. Hence they are 'null' with above exception. Ideally UpperCaseAlphaLength1to3 & OTA_CodeType should be defined in the XSD.  We could tolerate undefined memberTypes which are resulting as  'null' in the code by checking for 'null', but it could have other repercussion since ideally if type is referred in the schema, it's expected to be defined in the schema.
