### ISSUE TITLE
Unable to add custom namespace to body tags.

### ISSUE THREAD

**Issue by plinkpaste** [strongloop/strong-soap#112]
Hi, the SOAP server I'm trying to talk to requires body tags to have a namespace of `ldb`, so my request arguments look like this:

```
var args = {
    'ldb:numRows': 5,
    'ldb:crs': req.params.crs
};
```

However, the resulting XML doesn't include these namespaces:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <AccessToken>
      <TokenValue>REDACTED</TokenValue>
    </AccessToken>
  </soap:Header>
  <soap:Body>
    <numRows>5</numRows>
    <crs>MAN</crs>
  </soap:Body>
</soap:Envelope>
```

How can I add the namespace to the tags? The SOAP service sends an error back without them.

**Comment by AdrianP94** [comment]
Same issue, any solution?

**Comment by shahravir** [comment]
Hi Adrian,

The issue was with the multipart WSDL where the wsdl:part and wsdl:input names were different (variable names). I updated wsdl with this cosmetic change and it works as expected.

Thanks,
Ravi Shah

**Comment by gugahoi** [comment]
I am looking for how to achieve this as well. For some reason the library is extracting the namespace despite me giving it in the arguments:

```
let request = {
    'ved:request': {
        'ved:enquiry-header': {
            'ved:permission-type-code': 'X',
            'ved:product-data-level-code': 'C',
        },
    },
}
```

However this is what gets sent in the request:
```
  <soap:Body>
    <request>
      <enquiry-header>
        <permission-type-code>X</permission-type-code>
        <product-data-level-code>C</product-data-level-code>
      </enquiry-header>
    </request>
  </soap:Body>

```
