### ISSUE TITLE
No date conversion while parsing server input message

### ISSUE THREAD

**Issue by vasyas** [strongloop/strong-soap#114]
It could be because XmlHandler.xmlToJson is called without supplied descriptors.

**Comment by rashmihunt** [comment]
@vasyas can you send a test case to reproducing the issue?

**Comment by aladinnnus** [comment]
I have probably the same error the response a get from my API include a date and it's got instead of a date Invalide Date

**Comment by Simobain** [comment]
Hi !

I'm dealing with a soap API and all the returned dates are considered invalid. Is it possible to get a string instead ?
@rashmihunt thanks for your help !

**Comment by Simobain** [comment]
The answer is simple :
try the date conversion before converting it :
line 740, file https://github.com/strongloop/strong-soap/blob/master/src/parser/xmlHandler.js

```
if (jsType === Date) {
    value = new Date(text);
    if (!value.getMonth()){
         value = text;
    }
}
```

**Comment by aladinnnus** [comment]
EDIT: It's working i tried it

**Comment by aladinnnus** [comment]
just did a pull request
