### ISSUE TITLE
examples are not working

### ISSUE THREAD

**Issue by dottgonzo** [strongloop/strong-soap#122]
This is the first time i use this module, so maybe my tests are wrong.

I've tried the module with the examples present on this repo (/example/weather.js and example/stockquote.js), with my pc (Ubuntu x86_64 16.04, node 6.11.2, npm 5.3.

i've cloned the repo, installed everithing with "npm install" and then i runs the examples with this results:

$ node example/stockquote.js

Response Envelope:
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><GetQuoteResponse xmlns="http://www.webserviceX.NET/"><GetQuoteResult>exception</GetQuoteResult></GetQuoteResponse></soap:Body></soap:Envelope>
Result:
{"GetQuoteResult":"exception"}

so {"GetQuoteResult":"exception"} seems an error derived by something changed on the service used for this example

and

$ node example/weather.js

return the error:

TypeError: Cannot read property 'Weather' of undefined

Hope that this warning can be helpful. Is really useful to have some examples to learn how the module works

**Comment by dhmlau** [comment]
@dottgonzo , sorry about the late response.  As far as I know, the weather and stockquote web services no longer exist.  Would you like to submit a patch for using some existing web services instead?
