### ISSUE TITLE
Using Strong-Soap with Ionic 2

### ISSUE THREAD

**Issue by hoffmanjon** [strongloop/strong-soap#128]
I apologize that this is not really an issue but not sure where I can ask this question.  I need to add a soap client to an Ionic 2 application.  I added strong soap to my application using 'npm install strong-soap --save'.  then at the top of my typescript file I added:

`import * as sSoap from 'strong-soap';`

But when I make the createClient call the application crashes.  The createClient function call looks like this:
```
var url = 'http://www.webservicex.net/stockquote.asmx?WSDL';

var requestArgs = {
  symbol: 'IBM'
};
sSoap.createClient(url, options, function(err, client){
});
```

Has anyone been able to get strong-soap working with ionic 2?
thanks,

**Comment by daesign-dev** [comment]
Can you try ?
```
sSoap.soap.createClient(url, options, function(err, client){
});
```

**Comment by sdete** [comment]
Does it work ?

```
sSoap.soap.createClient(url, options, function(err, client){
});
```

**Comment by hudsontavares** [comment]
You can try to import it as

`import { soap } from 'strong-soap;`
