### ISSUE TITLE
Issue with WSSecurity PasswordDigest

### ISSUE THREAD

**Issue by tolland** [strongloop/strong-soap#131]
Hi,
(I am new to nodejs, so apologies if I have missed anything basic...)

I have been working with the onvif web service that exists on come cctv cameras. I was previously using the node-onvif package, but switched to strong-soap for greater flexibility. When using non-authenticated services, I am able to use strong-soap fine. However I get authentication errors when trying to add the WSSecurity tokens with strong-soap.

There looks to be an issue with the way the passwordDigest is creating the sha-1 hash [in utils.js](https://github.com/strongloop/strong-soap/blob/master/src/utils.js#L4);
```javascript
exports.passwordDigest = function passwordDigest(nonce, created, password) {
  // digest = base64 ( sha1 ( nonce + created + password ) )  
  var pwHash = crypto.createHash('sha1');  
  var rawNonce = new Buffer(nonce || '', 'base64').toString('binary');  
  pwHash.update(rawNonce + created + password);  
  return pwHash.digest('base64');  
};
```

It's not clear to me what `new Buffer(nonce || '', 'base64').toString('binary')` actually produces, and whether it makes sense to concatenate that to a UTF8 string in `pwHash.update(rawNonce + created + password); `

I looked at the way [node-onvif is doing it](https://github.com/futomi/node-onvif/blob/master/lib/modules/soap.js#L238), and came up with this alternative which seems to allow strong-soap to authenticate to a variety of ONVIF cameras requiring WSSecurity passwordDigest;

```javascript
exports.passwordDigest = function (nonce, created, password) {
  // digest = base64 ( sha1 ( nonce + created + password ) )
  var pwHash = crypto.createHash('sha1');
  var rawNonce = new Buffer(nonce || '', 'base64');
  pwHash.update(Buffer.concat([
    rawNonce,
    new Buffer(created),
    new Buffer(password)
  ]));
  return pwHash.digest('base64');
};
```

I'll have a look and see if there is any way to test the output of those functions against a reference implementation of the WSSecurity password digest

**Comment by patrickmichalina** [comment]
@tolland how are you even getting the WSDL to work with this client!? I cannot get any service methods to populate inside the client.
