### ISSUE TITLE
Elements defined in an included xsd file are not found by the wsdl parser

### ISSUE THREAD

**Issue by ziadloo** [strongloop/strong-soap#137]
# Description/Steps to reproduce
First of all, I believe this is a bug. Secondly, as for the steps to replicate the issue, here's the conceptual way to do so:

1. Have a WSDL with external xsd schema file(s) included
2. Create a SOAP client based on that WSDL

And here are the steps based on the provided [test_case.zip](https://github.com/strongloop/strong-soap/files/1606925/test_case.zip):
1. `$ cd test_case`
2. `$ npm install`
3. `$ node ./src/strong-client.js`

What I found myself debugging the code is that, it seems like even though the schema for `rps:ES2-GetEISRequest` is provided in the `euicc.request.ES2.xsd` but it's not accessible to the wsdl's parser at `node_modules/strong-soap/src/parser/element.js:184` where `resolveSchemaObject(schemas, elementType, nsName)` is trying to populate `part.element` with that. This is not resulting in an error on its own. But later, down the line when the `part` is being created, the following error occurs:

```
AssertionError [ERR_ASSERTION]: Document/literal part should use element
    at Operation.getMode (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl/operation.js:349:11)
    at Operation.postProcess (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl/operation.js:65:12)
    at Binding.postProcess (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl/binding.js:60:17)
    at Service.postProcess (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl/service.js:22:19)
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:69:25
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:189:9
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:189:9
    at WSDL._processNextInclude (/home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:157:14)
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:188:12
    at /home/mehran/test_case/node_modules/strong-soap/src/parser/wsdl.js:101:9
```

# Link to reproduction sandbox

This is an issue with SOAP client. I'm not sure if a sandbox applies here. In any case, I've attached a [test_case.zip](https://github.com/strongloop/strong-soap/files/1606925/test_case.zip) to the issue.

# Expected result

I couldn't run the code ever to say what exactly it should return but simply put, it should show the loaded `client` as the second parameter of the function's arguments.

# Additional information

It's also worth noting that the provided WSDL file can be used in SOAP-UI without any problems.

```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'`
linux x64 9.3.0
$ npm ls --prod --depth 0 | grep loopback
(nothing)
```

**Comment by ziadloo** [comment]
Hi @raymondfeng,

Thanks for the quick patch. It fixes the problem given in the test case. But as I was testing it I faced another case where your provided patch does not fix (I'm not sure if you are done with it or not). I thought now that you are at it, I should give you another test case so your patch will be complete. Please find it here: 

[test_case_2.zip](https://github.com/strongloop/strong-soap/files/1609516/test_case_2.zip)

This is pretty close to the previous case the only difference is that this time the `rps:ES2-GetEISRequest` element is defined two level deep in an XSD file. The main WSDL includes `xsd/euicc.request.ES2.xsd` and while it is including `euicc.request.ES2.2.xsd` in turn. And it's this late XSD file that holds the definition for the mentioned element. And again, like before, this element's definition can not be found in `schema.elements` collection and thus the same error occurs.

Thank you,
Mehran

**Comment by raymondfeng** [comment]
I have pushed a new fix under https://github.com/strongloop/strong-soap/pull/138. Pls try again.

**Comment by ziadloo** [comment]
Thank you so much, @raymondfeng. It seems to me that it's working.
