### ISSUE TITLE
client.describe() not returning all the information available in the WSDL.

### ISSUE THREAD

**Issue by bhavnagyanchandani** [strongloop/strong-soap#151]
I am using this "strong-soap" node module with Workday WSDL and the link for which is available here -https://community.workday.com/sites/default/files/file-hosting/productionapi/Learning/v29.1/Learning.html.

PFA the screenshot from the WSDL:

![image](https://user-images.githubusercontent.com/17310585/37718075-e0bb2b48-2d47-11e8-9766-5758c93a32a2.png)

But the response from the client.describe() does not return information about the description, minOccurs and maxOccurs. 
Could someone please look into it?

**Comment by bhavnagyanchandani** [comment]
@raymondfeng - I have tried with simple WSDL. PFA the WSDL I have tried.
[SampleDummy.zip](https://github.com/strongloop/strong-soap/files/1847576/SampleDummy.zip)
I have also tried to print the below for further lookup:

1. client.wsdl.definitions.schemas
2. client.wsdl.definitions.schemas["http://Example.org"].elements.Add.parent.elements.AddResponse

But in the results, I didn't find the information about _**minOccurs**_ which is available in the WSDL.

Could you please help me in understanding whether I am trying to access the value in correct way?
Also, if the above approach is incorrect, could you please help me understanding how would I fetch the required information from the client.

**Comment by bhavnagyanchandani** [comment]
@raymondfeng - Further update on trying out Workday WSDL with this node nodule -
I have tried to print the below for further lookup: 
**_client.wsdl.definitions.schemas_**
But in the results, I didn't find the information about **_minOccurs, maxOccurs, description_** which is available in the WSDL. Please help us to understand on how we fetch that information from the SOAP client.

**Comment by raymondfeng** [comment]
@bhavnagyanchandani Such as attributes should be available as `$minOccurs` and `$maxOccurs`.

**Comment by bhavnagyanchandani** [comment]
@raymondfeng - I tried accessing the minOccur and maxOccur attributes of the element as shown in below screenshot.
![image](https://user-images.githubusercontent.com/17310585/38048154-42642b16-32e2-11e8-871e-822dee292c63.png)

Now, here to access attributes of one such element, I have to iterate the children and using dot notation, I have to fetch the attributes.
But when using this node module with working endpoint WSDL, where I am trying the generate the loopback model, for each property, I need to iterate over the children (around 4-5 levels down) and get its respective attributes.

In case of a complex model, doing it for each property, it would take lot of iterations, which would impact the performance.

I wanted to understand is there any way out using which if I pass the property name (element-name) and I should be getting all its attributes easily with one single call. 
is it something already in place which I am missing here? Could you please help.

**Comment by bhavnagyanchandani** [comment]
@raymondfeng - Also, I tried accesing the documentation from the WSDL,
PFB the screenshot of the WSDL:
![image](https://user-images.githubusercontent.com/17310585/38075049-925d365a-334e-11e8-9ff0-506c05eae2c7.png)
We need this for adding description in the LoopBack model, but we are unable to get its value. Could you please guide me on how to access the value of documentation field as well.

**Comment by bhavnagyanchandani** [comment]
This issue seems to be fixed now and I am now able to access the description.Hence, closing this issue.
