### ISSUE TITLE
Array argument support for strong-soap

### ISSUE THREAD

**Issue by candam** [strongloop/strong-soap#158]
# Description/Steps to reproduce
Hello I'd like to ask for supporting array cause the api I'm trying to connect to 
is currently expecting array 

    Shipments: ['3915342793', '3915342826']
The generated xml for the request is 
    <ns1:Shipments/> 
is empty because strong soap cannot read array types

**Comment by arkore** [comment]
Try this and see if it works for you

`Shipments: [{$value: '3915342793'}, {$value: '3915342826'}]`

This will produce two ns1:Shipments tags. If the shipment ID's should be in child tags then

`Shipments: {ShipmentIDs: [{$value: '3915342793'}, {$value: '3915342826'}]}`

Which will produce
<ns1:Shipments>
  <ns1:ShipmentIDs></ns1:ShipmentIDs>
  <ns1:ShipmentIDs></ns1:ShipmentIDs>
</ns1:Shipments>

This should be included in the docs

**Comment by LiamKarlMitchell** [comment]
For me something like this worked.

```
{
  types: {
    item: ['a', 'b', 'c']
  }
}
```
Ended up giving the server what it expected of an ArrayOfString.

Magento 1 catalogProductAttributeMediaCreate types array.
