### ISSUE TITLE
The signature or decryption was invalid

### ISSUE THREAD

**Issue by yushaUzumo** [strongloop/strong-soap#163]
I am getting the error: "The signature or decryption was invalid" when i use strong-soap to access a service. Here is my code:

`
"use strict";

var fs = require('fs');
var base = process.env.PWD;

var publicKey = fs.readFileSync(base + "/cert.pem", "utf8");
var privateKey = fs.readFileSync(base + "/key.pem", "utf8");
var ca = fs.readFileSync(base + "/msservices.pem", "utf8");
var password = "mypassphrase";

var soap = require('strong-soap').soap;

var url = 'http://www.microsoft.com:4433/MicrosoftServices2/MSService?wsdl';

var options = {};

var requestArgs = {};

soap.createClient(url,options,function(err, client) {

	var wsSecurity = new soap.WSSecurityCert(privateKey,publicKey, password)
	client.setSecurity(wsSecurity);

	
	
	
	client.getDealerBalance(requestArgs, function(err, result, envelope) {
		//console.log(JSON.stringify(result));
		console.log(result);
	});
	
});
	
`

Below is the xml in the body of the result. By looking at my code what am I doing wrong?

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Body><soap:Fault><soap:Code><soap:Value>soap:Sender</soap:Value><soap:Subcode><soap:Value xmlns:ns1="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">ns1:FailedCheck</soap:Value></soap:Subcode></soap:Code><soap:Reason><soap:Text xml:lang="en"># The signature or decryption was invalid</soap:Text></soap:Reason></soap:Fault></soap:Body></soap:Envelope>

What must I change in my code to resolve this error?

**Comment by raymondfeng** [comment]
You can turn on debug by setting env var `DEBUG=strong-soap:client` to check what SOAP request is sent.
