### ISSUE TITLE
How to set timeout of request

### ISSUE THREAD

**Issue by Runrioter** [strongloop/strong-soap#164]
How to set timeout of request?

**Comment by dhmlau** [comment]
@Runrioter , are you looking for this? https://github.com/strongloop/strong-soap#clientserviceportmethodargs-callback-options-extraheaders

**Comment by Runrioter** [comment]
@dhmlau  thanks for your reply. Is it ok like this? https://github.com/Runrioter/id5/blob/fa9f9452252553a77250cc51ce1d714259a60e27/index.js#L37
