### ISSUE TITLE
Support to send soapAction for SOAP 1.2 service invocation

### ISSUE THREAD

**Issue by vineet-jain** [strongloop/strong-soap#170]
Ran into issue while trying to consume SOAP 1.2 service. After debugging identified that soapAction header is not sent through for that operation in case of SOAP 1.2, while it is present in case of invocation of SOAP 1.1 service. 

Expectation - soapAction should be sent as part of headers in case of invocation of SOAP 1.2 service as well. If not sent always it should be driven if WSDL has defined the soapActionRequired is ‘true’ for that operation.

**Comment by dhmlau** [comment]
Closing this issue as PR #171 has landed, and strong-soap@1.13.2 is released. 
@vineet-jain, thanks for your contribution! 🎉
