### ISSUE TITLE
Write JSDocs for xmlHandler function

### ISSUE THREAD

**Issue by b-admike** [strongloop/strong-soap#174]
# Description/Steps to reproduce

Right now, it is not clear what `xmlHandler` takes in for parameters without digging into the code. This task is to add JSDocs for the function so it is easier to understand for developers working with it.

**Comment by dhmlau** [comment]
@b-admike, do we still need this? Thanks.

**Comment by b-admike** [comment]
@dhmlau I don't think so, but can be revisited on future requests.
