### ISSUE TITLE
XML Deserialization with an XML schema

### ISSUE THREAD

**Issue by b-admike** [strongloop/strong-soap#178]
## Description/Steps to reproduce

Given an XML document and XML schema, I would like to deserialize it to a JSON object (how does it differ from XML write functionality without xml schema?).

**Comment by dhmlau** [comment]
@b-admike, do we still need this? Thanks.

**Comment by b-admike** [comment]
@dhmlau I believe this functionality already exists. cc @raymondfeng. Feel free to re-open if not.
