### ISSUE TITLE
WSDL in OBS service , strong-soap request  formatting issue but able to consume same service using soap UI client

### ISSUE THREAD

**Issue by Dhimanboy** [strongloop/strong-soap#179]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by raymondfeng** [comment]
@Dhimanboy Please provide more information, such as the WSDL and expected vs. produced SOAP request.

**Comment by Dhimanboy** [comment]
@raymondfeng  thanks for your response 
issue is resolved

Json request was not in correct format

was sending request as below ;

{
key1 :"",
key2 :""
..
} 

correct format as below

{
"parentKey":{
key1:"",
key2:""
}
}
was not added parent key as defined in xsd .
