### ISSUE TITLE
unable to parse wsdl due to missing part.element

### ISSUE THREAD

**Issue by alexcorre** [strongloop/strong-soap#180]
# Description/Steps to reproduce

I believe this to be a bug since SOAP-UI is able to parse the .wsdl file in question. I'm having trouble pinpointing the exact point of failure during parse, but the following steps demonstrate inability to parse the given .wsdl file making use of the included `strongsoaptest.zip` below.

```
$ node --version
v8.9.4
```

1. Download and unzip `strongsoaptest.zip` (below).
2. `cd strongsoaptest`
3. `npm install`
4. `node index.js` 

The issue looks similar to #137 though the fix in #147 does not fix this parsing issue. Looks like `part.element` is not defined when the `Operation` is being created due to previous inability to resolve the element type of the part.

```
Error: Document/literal part should use element
    at Operation.getMode (/Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl/operation.js:351:19)
    at Operation.postProcess (/Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl/operation.js:65:12)
    at Binding.postProcess (/Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl/binding.js:60:17)
    at Service.postProcess (/Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl/service.js:22:19)
    at /Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl.js:73:25
    at /Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl.js:207:9
    at /Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl.js:207:9
    at /Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl.js:207:9
    at /Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl.js:207:9
    at WSDL._processNextInclude (/Users/alexcorre/dev/strongsoaptest/node_modules/strong-soap/src/parser/wsdl.js:162:14)
``` 

# Link to reproduction sandbox
[strongsoaptest.zip](https://github.com/strongloop/strong-soap/files/2291906/strongsoaptest.zip)

# Expected result

No error returned to callback. Instead a working client instance is created.

# Additional information

Worth noting that the wsdl file included in the zip example is a trimmed down version of the full wsdl file available here, which also works well with SOAP UI

https://api.alliancepayroll.info/AllPayData.svc?wsdl

**Comment by alexcorre** [comment]
closing. will reopen with a better example.

**Comment by Axel-CH** [comment]
Hi @alexcorre , I have the same issue, did you found a workaround?
