### ISSUE TITLE
feature request: define outgoing SOAP headers per operation not client

### ISSUE THREAD

**Issue by alexcorre** [strongloop/strong-soap#181]
# Description/Steps to reproduce

First off, been using strong-soap for the past year implementing a number of integrations and its been great! Much less trouble and more reliable than the incumbent `soap` lib.

My team is working with an API that requires SOAP [Addressing](https://www.w3.org/Submission/ws-addressing/). Specifically requests are denied if they do not include the soap headers `To` and `Address`. In order to support the Addressing SOAP headers `To` and `Action`.

For example we are making requests to the service defined at https://api.alliancepayroll.info/AllPayData.svc?wsdl (Note: this wsdl out of the box is not parsed correctly by strongsoap, will be filing another ticket to address that)

Using `strong-soap` to do the following, results in a denied request:

```js
client.CPortal({
   authorization: {
      loginToken: null,
      username: 'SOME_USERNAME',
      password: 'SOME_PASSWORD',
      userType: 'AllPay',
   },
   // ... more stuff
});
```
Request Body:

```xml
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"> 
	<soap:Header /> 
	<soap:Body> 
		<ns1:CPortal xmlns:ns1="https://api.hralliance.net/"> 
			<ns1:authorization> 
				<ns2:loginToken xmlns:ns2="http://schemas.datacontract.org/2004/07/AllPayAPI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true" /> 
				<ns2:password xmlns:ns2="http://schemas.datacontract.org/2004/07/AllPayAPI">SOME_PASSWORD</ns2:password> 
				<ns2:userName xmlns:ns2="http://schemas.datacontract.org/2004/07/AllPayAPI">SOME_USERNAME</ns2:userName> 
				<ns2:userType xmlns:ns2="http://schemas.datacontract.org/2004/07/AllPayAPI">AllPay</ns2:userType> 
			</ns1:authorization> 
			<ns1:fieldsToPopulate>guidfield,portalname</ns1:fieldsToPopulate> 
			<ns1:sortOrder /> 
			<ns1:filter>FILTER_STRING</ns1:filter> 
			<ns1:queryOptions> 
				<ns2:batchSize xmlns:ns2="http://schemas.datacontract.org/2004/07/AllPayAPI">100</ns2:batchSize> 
				<ns2:queryIdentifier xmlns:ns2="http://schemas.datacontract.org/2004/07/AllPayAPI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true" /> 
				<ns2:startRecord xmlns:ns2="http://schemas.datacontract.org/2004/07/AllPayAPI">0</ns2:startRecord> 
			</ns1:queryOptions> 
		</ns1:CPortal> 
	</soap:Body> 
</soap:Envelope>
```

This web service requries that instead of an empty header, we provide the following:

```xml
<soap:Header xmlns:a="http://www.w3.org/2005/08/addressing">
    <a:Action soap:mustUnderstand="1">https://api.hralliance.net/IAllPayData/CPortal</a:Action> 
    <a:To soap:mustUnderstand="1">http://api.alliancepayroll.info/AllPayData.svc/V1</a:To
</soap:Header> 
```

In looking at the documentation we could achieve the `To` header using the `client.addSoapHeader()` API since this piece of information doesn't change per request.

The `Action` header is a bit different since it needs to reflect the soapAction from the operation at hand. For the example above, it needs to specify the soap action for `CPortal`.

Currently I saw two ways to modify the SOAPHeader but correct me if i'm wrong. 

1. client.addSoapHeader - Adds a header to all request envelope bodies make by this client. Not possible to modify on a per operation basis.
2. using a "Security" plugin class  with the `addSoapHeaders` method implemented. Allows per operation implementation, but only provides the existing soap header node to the function for modification.
 
Really what I want is automatic implementation of Addressing spec, but i think its more interesting to allow development of plugins that extend the soap body on a per request basis, with access to the current operation and the client itself. What I propose is to allow a generic mechanism for extending the outgoing envelope on a per request basis. 

I was able to achieve what I needed by extending the API of security plugins + storing the endpoint on the client upon initialization. 

You can see that in this diff:

https://github.com/strongloop/strong-soap/compare/master...Workpop:expanded-security-plugins

This works, but i'm not sure if this is really the job of a "security" extension since its not related to security. Since my team needed this now, we're using this fork in production temporarily until we can hopefully get a new feature merged into strong-soap.

This diff above allowed us to implement the following Security extension which adds the proper addressing headers on a per operation basis. 

```js
const W3_ADDRESSING_NAMESPACE = 'http://www.w3.org/2005/08/addressing';
const ADDRESSING_ALIAS = 'a';

export default class AddressingExtension {

  constructor({
    envelopeKey = 'soap',
  }) {
    this._soapNS = envelopeKey;
  }

  addSoapHeaders(header, client, operation) {
    // add addressing namespace to header
    header.attribute(`xmlns:${ADDRESSING_ALIAS}`, W3_ADDRESSING_NAMESPACE);

    // add Action SOAP Header
    header
      .element(`${ADDRESSING_ALIAS}:Action`, operation.soapAction)
      .attribute(`${this._soapNS}:mustUnderstand`, '1');

    // add To SOAP header
    header
      .element(`${ADDRESSING_ALIAS}:To`, client.endpoint)
      .attribute(`${this._soapNS}:mustUnderstand`, '1');
  }

}

```

This can be used simply:

```js
client.setSecurity(new AddressingExtension({envelopeKey: 'soap'}))
```

Downside here is that it would not be possible to set a second security instance here, but luckily it was not needed for our implementation.

My question to you is, whats the right way to achieve this extension ability on a per operation basis? Would be happy to put together a PR and tests to enable an implementation of addressing!

# Additional information

Thanks for taking the time!

**Comment by raymondfeng** [comment]
@alexcorre Thank you for the detailed description. I think it's a good idea to generalize `security` related hooks into plugins (such as client.setPlugin) for other purposes. The `client.setSecurity` api stays as a wrapper to the `setPlugin`.

If you can submit a PR, we'll work with you to get it merged and released. Thanks in advance.

**Comment by alexcorre** [comment]
thanks @raymondfeng.  I'll take a stab at it and we can go from there.
