### ISSUE TITLE
Sending MTOM Attachments

### ISSUE THREAD

**Issue by mckaycr** [strongloop/strong-soap#185]
# Description/Steps to reproduce

I'm trying to submit an MTOM attachment through the soap client, I have no idea how to accomplish it

# Link to reproduction sandbox

# Expected result

Some pointers or syntax that might help

# Additional information

[The system I'm trying to interface with](https://www.npdb.hrsa.gov/software/QRXSWebServiceUserGuide.pdf)

**Comment by arpentnoir** [comment]
+1 
I'm in the same boat

**Comment by mckaycr** [comment]
> +1
> I'm in the same boat

I found a second option.  The service I write too accepts files in two methods, one is a MTOM attachment, and the other is to include a files element where each file is encoded in base64 and then placed into an array.  That was a lot easier than hunting down some method for attaching MTOM.

**Comment by maccyber** [comment]
Does not seem like MTOM is supported in strong-soap.

ws.js was the only library I could find that supports it, but i had to patch it to work: https://www.npmjs.com/package/ws.js-buffer-fix

It's old and fugly, but seems like the only way to go if you don't want to write it yourself.

**Comment by chrisgh1** [comment]
Interested in mtom support also.  Is this on the road map?  Also I'm currently using ws.js but it looks like the project may have been abandoned.  I'm also having an issue with it with large files ie files in the 500MB rang and above. @maccyber I see your link has ws.js-buffer-fix could you elaborate on the "buffer fix"?  I'm wondering if this would resolve my issue with the large files.

**Comment by milesje** [comment]
I'm also interested in MTOM support for both sending and receiving!

**Comment by raymondfeng** [comment]
Unfortunately we don't hand bandwidth to implement MTOM support, but contributions are welcome!

**Comment by adi-gabrielli** [comment]
Node-soap has a support for sending MTOM requests via this: https://github.com/vpulim/node-soap/pull/1054
On the server side there is no implementation so I had to write some middleware to handle the request. Something along these lines ( i have a gzipped file attachment here which I temporarily save to some folder and I edit the SOAP xml to hold the path to the temp file ... bullshit standard): 
```
var multiparty = require('multiparty');
const { ungzip } = require('node-gzip');
var convert = require('xml-js');
function MOTMhandler (req, res, next){
    var response = "";
    if (req.headers["content-type"] && req.headers["content-type"].indexOf("multipart") > -1) {
        var form = new multiparty.Form({
            uploadDir: "/tmp/temp_upload"
        });
        form.parse(req, (err, fields, files) => {
            let field_key = Object.keys(fields)[0];
            let file_key = Object.keys(files)[0];
            

            var res_xml = convert.xml2js(fields[field_key][0]);

            const filedata = fs.readFileSync(files[file_key][0].path);
            ungzip(filedata)
            .then( (uncompressed) => {
                fs.writeFile(files[file_key][0].path+"_uncompressed", uncompressed, (err) => {
                    fs.unlink(files[file_key][0].path, () => {} );
                  
                    const stats = fs.statSync(files[file_key][0].path+"_uncompressed");
                    var fileSizeElement = {
                        type: "element",
                        name: "originalFileSize",
                        elements: [{
                            type: "text",
                            text: stats.size
                        }]
                    }

                    var filePathElement = {
                        type: "element",
                        name: "tempFilePath",
                        elements: [{
                            type: "text",
                            text: files[file_key][0].path + "_uncompressed"
                        }]
                    }

                    var fileNameElement = {
                        type: "element",
                        name: "originalFileName",
                        elements: [{
                            type: "text",
                            text: files[file_key][0].originalFilename
                        }]
                    }

                    res_xml.elements[0].elements[1].elements[0].elements.push(fileNameElement);
                    res_xml.elements[0].elements[1].elements[0].elements.push(filePathElement);
                    res_xml.elements[0].elements[1].elements[0].elements.push(fileSizeElement);

                    response = convert.js2xml(res_xml);
                    req.body = response;
                    next()
                })
            })
        })
    } else {
        next()
    }
}
```

**Comment by allanmayanei1** [comment]
> Infelizmente não temos largura de banda para implementar o suporte MTOM, mas contribuições são bem vindas!

I made this contribution on the fork: [add attachments](https://github.com/allanmayanei1/strong-soap) how to pull requests
