### ISSUE TITLE
XSD element order issue

### ISSUE THREAD

**Issue by RandyWilkinson** [strongloop/strong-soap#187]
# Description
I see that there was a fix roughly 7 months ago for element ordering and most of the tests center around nested and inherited complex type sub elements. But I have a simple method parameter with elements that are being produced in the wrong order. This results in the web-service not being able to deserialize the parameters correctly. 

Simple imported complex type:
```
<xs:complexType name="getWorkflowLock">
   <xs:sequence>
      <xs:element type="xs:string" name="pWorkflowId" minOccurs="0"/>
      <xs:element type="xs:string" name="pTableName" minOccurs="0"/>
      <xs:element type="xs:string" name="pTarget" minOccurs="0"/>
   </xs:sequence>
</xs:complexType>
```
Building and passing this json:
```
const requestParam = {
            pWorkflowId: "12",
            pTablename: "TestTable",
            pTarget: "6238",
        };
```
Produces this request:
```
<ns1:getWorkflowLock xmlns:ns1="http://workflowmanager.webservice.com/">
      <pWorkflowId>12</pWorkflowId>
      <pTarget>6238</pTarget>
      <pTablename>TestTable</pTablename>
    </ns1:getWorkflowLock>
```

# Link to reproduction sandbox
I have created a very simple demonstration of this issue here:
[strong-soap_sample.zip](https://github.com/strongloop/strong-soap/files/2377047/strong-soap_sample.zip)

# Expected result
```
<ns1:getWorkflowLock xmlns:ns1="http://workflowmanager.webservice.com/">
      <pWorkflowId>12</pWorkflowId>
      <pTablename>TestTable</pTablename>
      <pTarget>6238</pTarget>
    </ns1:getWorkflowLock>

```

# Additional information
node -e 'console.log(process.platform, process.arch, process.versions.node)' -> win32 x64 8.11.3

**Comment by RandyWilkinson** [comment]
Xml element order is such a basic requirement for all XSD sequence definitions, I am not sure how anyone else is using this library. Has anyone else encountered this issue?

**Comment by adampenn** [comment]
Looking at the `requestArgs` object in `app.js` it looks like `pTablename` actually needs to be `pTableName` like you have defined in `WorkflowManagerService_schema.xsd`.

**Comment by RandyWilkinson** [comment]
Ah, yes, that fixed it. So I guess additional request arguments not defined in the XSD are allowed and pushed to the end of the request argument. Struggled with this one for a while, thanks.
