### ISSUE TITLE
How to send a provide the SOAP Request for the call

### ISSUE THREAD

**Issue by SomannaDC** [strongloop/strong-soap#194]
I have a SOAP XML String which i need to pass to the SOAP call, how do i provide it? There is no help in the documentation.

**Comment by milesje** [comment]
The only way I found to do this was to use the XMLHandler to transform it to JSON and then pass that into the client call.

```
var XMLHandler = soap.XMLHandler;
var xmlHandler = new XMLHandler();
var xml = fs.readFileSync("/location/of/file.xml").toString()
var json = xmlHandler.xmlToJson(null, xml, null)
client.method(json, function(err, result){
}
```
