### ISSUE TITLE
TypeError: nodeVersion is undefined

### ISSUE THREAD

**Issue by fuzunspm** [strongloop/strong-soap#214]
# Description/Steps to reproduce
I can't use it on ReactJS application with the error output below..

```
TypeError: nodeVersion is undefined
./node_modules/strong-soap/index.js/<
./node_modules/strong-soap/index.js:5

  2 | 
  3 | var base = './lib/';
  4 | var nodeVersion = process.versions.node;
> 5 | var major = Number(nodeVersion.split('.')[0]);
  6 | if (major >= 4) {
  7 |   base = './src/';
  8 | }
```
# Additional information
darwin x64 11.14.0
npm ERR! peer dep missing: preact@*, required by unistore@3.2.1

**Comment by raymondfeng** [comment]
The module is for Node.js. To make it browser compatible, a few things need to happen:

- Make refs to Node optional
- Make it possible to plug in an http client library compatible with browsers

**Comment by thw0rted** [comment]
Did this get closed because there are no plans to support this library in a browser environment?

(If so, can anybody suggest a browser-compatible alternative library?)
