### ISSUE TITLE
DeprecationWarning: Buffer()

### ISSUE THREAD

**Issue by JanzenPacker** [strongloop/strong-soap#217]
The use of `new Buffer()` is deprecated in NodeJS. (https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/)

Suggested change in [https://github.com/strongloop/strong-soap/blob/master/src/strip-bom.js](url) 

Current:
`var chunk = new Buffer(str);`

Request Change To:
`var chunk = Buffer.from(str);`

**Comment by raymondfeng** [comment]
@JanzenPacker Would you like to submit a PR?

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/strong-soap/commit/f8c559618251c39035b0c1c93d8e4b63c518ca8c
