### ISSUE TITLE
You should probably support 1,0,'1' or '0' as boolean values

### ISSUE THREAD

**Issue by smarotta** [strongloop/strong-soap#218]
https://github.com/strongloop/strong-soap/blob/74a83816caec1dea4eaaa539d9a3ce0626c1313a/src/parser/xmlHandler.js#L846

**Comment by smarotta** [comment]
more info on: http://www.datypic.com/sc/xsd/t-xsd_boolean.html

**Comment by raymondfeng** [comment]
@smarotta Would you like to submit a patch? I can help review and land it.

**Comment by smarotta** [comment]
Sure @raymondfeng

**Comment by dhmlau** [comment]
The PR #219 has merged. Closing this issue as done. @smarotta, thanks again for your contribution. 🎉
