### ISSUE TITLE
404

### ISSUE THREAD

**Issue by monu778** [strongloop/strong-soap#221]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
@monu778, are you encountering problems in this module?  Could you please elaborate on your question/problem? Thanks.

**Comment by dhmlau** [comment]
Looks like you've submitted another issue https://github.com/strongloop/strong-soap/issues/222.  Closing this in favor of https://github.com/strongloop/strong-soap/issues/222. Thanks.
