### ISSUE TITLE
Getting Status 404 error for given wsdl 

### ISSUE THREAD

**Issue by monu778** [strongloop/strong-soap#222]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by monu778** [comment]
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> &#47;axis2&#47;services&#47;Authorization</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.38</h3></body></html>

**Comment by monu778** [comment]
The same wsdl is working with easy-soap module. I liked this module mainly for proper parsing of soap repsonse

**Comment by dhmlau** [comment]
@raymondfeng , I'm not sure what's the use case here (or we have enough information), but I'm not familiar with this module either.  Could you please take a look? Thanks.

**Comment by raymondfeng** [comment]
What's the url for your wsdl? Can you access it from inside the browser?
