### ISSUE TITLE
Modifying the response body before it gets sent

### ISSUE THREAD

**Issue by adi-gabrielli** [strongloop/strong-soap#223]
# Description/Steps to reproduce
I have to send a MTOM response back to the client. So on the client side, the response is not a valid  SOAP xml but one on the parts of the response will be. As far as I can tell, the only way to do this is to write a middleware to change the output. 

```
function MOTMResponseHandler (req, res, next){
    let oldWrite = res.write;

    res.write = function(data){
        if (req.headers.soapaction && (req.headers.soapaction.indexOf("GetProject") >= 0) ){
            arguments[0]="changed respose body"
        }
        oldWrite.apply(this, arguments);
    }

    var oldEnd = res.end
    res.end = function() {
        if (req.headers.soapaction && (req.headers.soapaction.indexOf("GetProject") >= 0) )
            console.log('do something..');
        oldEnd.apply(this,arguments);
    }
    next();
}
```
This seems to do the trick for some test requests. In case of big requests _res.write_ will receive chuncked data, which means I can't handle the data in _res.write_. In _res.end_ there is no data to be handled.
Any ideas?

**Comment by mihir83in** [comment]
+1
