### ISSUE TITLE
Question: Server Security

### ISSUE THREAD

**Issue by milesje** [strongloop/strong-soap#229]
I see the example of using WSSecurityCert to connect to a Server that is using x.509 certs for security. So how do you create a server that uses the x.509 certs?
The only server side security I see is using server.authenticate and server.authorizeConnection.

**Comment by raymondfeng** [comment]
Please note that the server side support is experimental. You should try to use other stacks such as JAX-WS to create soap servers.

**Comment by dhmlau** [comment]
Closing this issue as answered. Thanks.
