### ISSUE TITLE
strong-soap server produces ns1 prefix for anonymous complex types

### ISSUE THREAD

**Issue by mihir83in** [strongloop/strong-soap#234]
Given a sample xsd,
```
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.java2s.com" xmlns="http://www.java2s.com"
  elementFormDefault="qualified">

  <xsd:element name="characteristics">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="weight" type="xsd:string" />
        <xsd:element name="length" type="xsd:string" />
      </xsd:sequence>
      <xsd:attribute name="kind" type="xsd:string" />

    </xsd:complexType>
  </xsd:element>
</xsd:schema>
```
strong-soap server generates something like
```
<?xml version="1.0"?>
<ns1:characteristics xmlns:ns1="http://www.java2s.com" kind="physical">
  <weight>3 points</weight>
  <length>3 years</length>
</characteristics>
```
while it should be generated as 
```
<?xml version="1.0"?>
<characteristics xmlns="http://www.java2s.com" kind="physical">
  <weight>3 points</weight>
  <length>3 years</length>
</characteristics>
```
That is without `ns1` prefix, or at least the prefix should be allowed to be removed by config.
I've tried looking into wsdl_options, nsContext and xmlHandler but can't figure this out

Help really appreciated, @rashmihunt

**Comment by bonnlei** [comment]
I have same problem by v 1.20.0

**Comment by darbyo** [comment]
Same problem for me!

**Comment by bohdan-zahaiskyi** [comment]
I have a same problem too! All namespaces from my wsdl in `NamespaceContext.namespaces` have `declared: false`. When `XMLHandler.jsonToXml()` is invoked, `if (mapping === null || mapping.declared === false)` check passes and NamespaceContext declares new namespace with generated prefix which is `ns1`. And because of that my soap request header and body contains wrong prefix.

**Comment by mihir83in** [comment]
+1
