### ISSUE TITLE
Can't get it work

### ISSUE THREAD

**Issue by fuzunspm** [strongloop/strong-soap#239]
# Description/Steps to reproduce

It throws error of 
```[0] TypeError: Cannot read property 'Login' of undefined```

It's working with JS but can't get it work on a typescript project

# Code

```
import { soap } from 'strong-soap';

const url = 'url';
const loginArgs = {
	login: {
		userName: 'username',
		passWord: 'password',
	},
};
const options = {};
soap.createClient(url, options, function(err, client) {
	const method = client['PostBoxService']['PostboxServiceEndpoint']['Login'];
	method(loginArgs, function(err, result, envelope, soapHeader) {
		const sessionID = result.sessionID;
		this.logger.debug(sessionID);
	})
});
```

darwin x64 10.15.3

**Comment by E-factor** [comment]
@fuzunspm  did you solve this?  i'm having the same issue (soap.createClient is returning nothing hence my operation is undefined)

**Comment by fuzunspm** [comment]
@E-factor I fixed my issue by converting it to arrow function like this

`method(loginArgs, (err, result, envelope, soapHeader) => {`

Sorry I’m on mobile but that way it worked.
