### ISSUE TITLE
node is recognized as simple type, if attribute is missing

### ISSUE THREAD

**Issue by cherzog** [strongloop/strong-soap#241]
# Description/Steps to reproduce
A node in the request is recognized as a simple type, if an (optional) attribute is missing. 

Have a look at: https://github.com/cherzog/strong-soap-test

# Current result

{ value: '200' }

# Expected result

{ value: { attributes: {  }, Value: '200' } }

**Comment by cherzog** [comment]
Maybe someone can tell me if this behavior is wanted or if it can be changed. I would take a look at it if necessary.

**Comment by raymondfeng** [comment]
Interesting. I would expect the result to be consistent. How does the xml schema for `value` look like?

**Comment by cherzog** [comment]
```xml
    <s:schema elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
      <s:element name="doSomething">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="value" type="tns:TextType" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="TextType">
        <s:simpleContent>
          <s:extension base="s:string">
            <s:attribute name="languageCode" type="s:language" />
          </s:extension>
        </s:simpleContent>
      </s:complexType>
      <s:element name="doSomethingResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="doSomethingResult" type="tns:TextType" />
          </s:sequence>
        </s:complexType>
      </s:element>
    </s:schema>
```

https://github.com/cherzog/strong-soap-test/blob/master/TestWSDL.xml

**Comment by raymondfeng** [comment]
Thanks. `TextType` is a complex type with a string value.

**Comment by cherzog** [comment]
Yes. And possibly an attribute.

**Comment by raymondfeng** [comment]
Would you please debug the issue to see what's wrong?

**Comment by cherzog** [comment]
The problem is here:
https://github.com/strongloop/strong-soap/blob/a51322e6a3911903d2c84d1d47d1fc7baf001ee5/src/parser/xmlHandler.js#L526

```javascript
  _processText(top, val) {
    // The parent element has xsi:nil = true
    if (top.object === null) return;
    // Top object has no other elements or attributes
    if (top.object === undefined) {
      top.object = val;
    } else if (top.object.constructor === Object) {
      // Top object already has attributes or elements
      let value = top.object[this.options.valueKey];
      if (value !== undefined) {
        top.object[this.options.valueKey] = value + val;
      } else {
        top.object[this.options.valueKey] = val;
      }
    } else {
      // Top object is other simple types, such as string or date
      top.object = top.object + val;
    }
  }
```
top.object is still undefined, because there is no attribute.

**Comment by raymondfeng** [comment]
@cherzog Good catch. Would you like to submit a patch?

**Comment by cherzog** [comment]
I want to try. At the moment I don't know how to find out that this is a ComplexType. I will probably have to evaluate the scheme...

**Comment by cherzog** [comment]
Is there already a function to get the type of the node?

I think the best place to implement is here: 
https://github.com/strongloop/strong-soap/blob/a51322e6a3911903d2c84d1d47d1fc7baf001ee5/src/parser/xmlHandler.js#L610

Something like:
```javascript

      if (elementAttributes) {
        obj = {};
        obj[self.options.attributesKey] = elementAttributes;
      } else {
        let isComplexTypeNode = false;
        // Howto find out, if the current node is a conplex type?
        
        if (isComplexTypeNode) {
          obj = {};
          obj[self.options.attributesKey] = {};
        } 
      }
```
If I manually set the value of _isComplexType_ to true, it already works as expected:
```
info Attempting to bind to /TestWSDL.asmx
info Trying TestWSDLSoap from path /TestWSDL.asmx
{ value: { attributes: { languageCode: '100' }, Value: '200' } }
200
replied <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ns1:doSomethingResponse xmlns:ns1="http://tempuri.org/">
      <value languageCode="100">200</value>
    </ns1:doSomethingResponse>
  </soap:Body>
</soap:Envelope>
```

Thanks for help.

**Comment by raymondfeng** [comment]
You should be able to check the [descriptor](https://github.com/strongloop/strong-soap/blob/a51322e6a3911903d2c84d1d47d1fc7baf001ee5/src/parser/xmlHandler.js#L554).

**Comment by cherzog** [comment]
Mmh, it's undefined.... 🤔

**Comment by cherzog** [comment]
https://github.com/strongloop/strong-soap/blob/a51322e6a3911903d2c84d1d47d1fc7baf001ee5/src/server.js#L137

**Comment by raymondfeng** [comment]
`server.js` is for the mock-up soap server only. If you run into the issue as a client for soap web services, you don't have to worry about that.

**Comment by cherzog** [comment]
"mock-up"? I want to use the server side. And it works (with the described exception).

**Comment by cherzog** [comment]
What are the reasons for not using the server productively?

Btw.: I really overread the "mock-up" in the README.md. ;-)
