### ISSUE TITLE
What are the advantages of strong-soap over node-soap

### ISSUE THREAD

**Issue by michaelbrawn** [strongloop/strong-soap#247]
# Additional information

Your readme mentions that this library is a complete rewrite of node-soap, but it doesn't give any information about why this was done. 

What are the advantages of strong-soap over node-soap?

**Comment by raymondfeng** [comment]
`strong-soap` fully leverages the WSDL/XSD information to control JSON/XML mapping respecting namespaces. The test coverage is much improved too.

**Comment by pink-raks** [comment]
In _strong-soap_ all xsds are referenced in the wsdl files are present in the WSDL_Cache. By this I can process all operations. 
But _node-soap_ does not support this. The WSDL_Cache only has the _first xsd_ which is a limitation.
It took us a day to figure out this problem and *strong-soap* was our savior.

**Comment by dhmlau** [comment]
Closing this issue as answered.
