### ISSUE TITLE
client.describe() not returning information related to minOccurs and documentation

### ISSUE THREAD

**Issue by nazimkh** [strongloop/strong-soap#251]
Hello,
I am using this node module to create a WSDL parser, and found out that there is a need to support following two missing information in the ``describe()`` method.

1. Whether an element is required or not by considering the minOccurs attribute. (Some what identical to isMany property of element which is present)
2. The ``describe()`` method should give the documentation information of the element as well.

I am aware the wsdl definitions schema would cover these two, but it would be more appropriate to have those two information in the ``describe()`` method.
@raymondfeng

**Comment by raymondfeng** [comment]
@nazimkh Are you willing to contribute a patch?

**Comment by deepakrkris** [comment]
@nazimkh are you referring to the `<xsd:documentation/>` tag (https://www.w3schools.com/xml/el_documentation.asp) ?

**Comment by raymondfeng** [comment]
@deepakrkris I think it's `<xs:annotation>`, which can contain `<xs:documentation>`. @nazimkh also asked for `minOccurs` attribute.

**Comment by deepakrkris** [comment]
@nazimkh is the ask for `minoccurs` in this issue from a documentation stand point ? or is there a validation missing in source code for minoccurs ?

**Comment by nazimkh** [comment]
@deepakrkris the `minoccurs` attribute will enable us to infer if the element in context is `required`  or not, for example if `minoccurs` value is `> 0` then we can say its `required`.
