### ISSUE TITLE
Possibility to send XML string directly instead of JSON requestArgs

### ISSUE THREAD

**Issue by zygimantus** [strongloop/strong-soap#254]
This is a duplicate of #238 , but still, it was unanswered.

Is it possible to send XML string directly instead of JSON requestArgs? Because in particular cases white-spaces and new lines are distorted using JSON requestArgs parameter and thus signed XML cannot be send using stong-soap.

**Comment by agnes512** [comment]
@raymondfeng could you take a look of the issue? thanks!

**Comment by deepakrkris** [comment]
> This is a duplicate of #238 , but still, it was unanswered.
> 
> Is it possible to send XML string directly instead of JSON requestArgs? Because in particular cases white-spaces and new lines are distorted using JSON requestArgs parameter and thus signed XML cannot be send using stong-soap.

@zygimantus If you are able to construct the xml independently without using strong-soap, you can use any http client to post the xml to a soap endpoint. There is no need of strong soap in that case.

**Comment by zygimantus** [comment]
@deepakrkris, thank you for response, that was exactly the way I did it.
