### ISSUE TITLE
Fault occurred while processing

### ISSUE THREAD

**Issue by Swagnus** [strongloop/strong-soap#255]
Hello.

I'm trying to use this node module as a client to consume functions from a SOAP API.
But no matter what i'm trying i'm getting the faultstring "Fault occurred while processing".
I believe this occurs because the request body seems to be empty. Shouldn't that be fetched from the WSDL by the module?

When i run the exact same thing through SoapUI it works as expected.

This API is unfortunately IP-locked from the API provider, so i can't provide a sandbox. I'm therefore pasting all requests and responses below along with the WSDL. Hope that's enough.

This is my code (see the WSDL/XML file attached as ZIP):
[wsdl.zip](https://github.com/strongloop/strong-soap/files/4096663/wsdl.zip)

```
var soap = require('strong-soap').soap;

var url = LINK_TO_WSDL;

soap.createClient(url, {}, function(err, client) {
    client.getServiceCatalogueList(function(err, result, envelope) {
        console.log('Envelope', envelope);
    });
});
```

This is the request generated by strong-soap:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body/>
</soap:Envelope>
```

This is the envelope response from strong-soap:
```
<env:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
   <faultcode xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/">ns1:Server</faultcode>
   <faultstring>Fault occurred while processing.</faultstring>
</env:Fault></env:Body></env:Envelope>
```

This is the request generated by SoapUI:
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v4="http://petra.linkon.se/commoncomplexelements/data/v4_7" xmlns:v41="http://petra.linkon.se/commonelements/data/v4_7" xmlns:v1="http://petra.linkon.se/additionalproducts/servicecataloguelist/data/v1_7">
   <soapenv:Header>
      <v4:ClientInformation>
         <v4:SalesUnitKey>?</v4:SalesUnitKey>
         <v4:ApplicationName>?</v4:ApplicationName>
         <!--Optional:-->
         <v41:LanguageCode>?</v41:LanguageCode>
         <!--Optional:-->
         <v4:EndUserId>?</v4:EndUserId>
         <!--Optional:-->
         <v4:RequestId>?</v4:RequestId>
         <!--Optional:-->
         <v4:InternalRequestId>?</v4:InternalRequestId>
         <!--Optional:-->
         <v4:TransactionLogging>?</v4:TransactionLogging>
         <!--Optional:-->
         <v4:__p2sInternal>?</v4:__p2sInternal>
         <!--Optional:-->
         <v4:__p2sInternalCallerPrincipal>
            <!--Optional:-->
            <v4:name>?</v4:name>
            <!--Optional:-->
            <v4:salesUnitKey>?</v4:salesUnitKey>
            <!--Optional:-->
            <v4:salesChannelType>?</v4:salesChannelType>
            <!--Optional:-->
            <v4:salesPointNumber>?</v4:salesPointNumber>
            <!--Optional:-->
            <v4:salesPointUnitNumber>?</v4:salesPointUnitNumber>
            <!--Optional:-->
            <v4:salesPointCategory>?</v4:salesPointCategory>
            <!--Optional:-->
            <v4:languageCode>?</v4:languageCode>
            <!--Optional:-->
            <v4:currencyCode>?</v4:currencyCode>
            <!--Optional:-->
            <v4:salesChannelCode>?</v4:salesChannelCode>
            <!--Optional:-->
            <v4:cardSystem>?</v4:cardSystem>
            <!--Optional:-->
            <v4:endUserId>?</v4:endUserId>
            <!--Optional:-->
            <v4:operationName>?</v4:operationName>
            <!--Optional:-->
            <v4:requestId>?</v4:requestId>
            <!--Optional:-->
            <v4:internalRequestId>?</v4:internalRequestId>
            <!--Optional:-->
            <v4:transactionLogging>?</v4:transactionLogging>
            <!--Optional:-->
            <v4:timeout>?</v4:timeout>
         </v4:__p2sInternalCallerPrincipal>
      </v4:ClientInformation>
   </soapenv:Header>
   <soapenv:Body>
      <v1:ServiceCatalogueListRequest/>
   </soapenv:Body>
</soapenv:Envelope>
```

This is the response (as expected) from SoapUI:
```
<env:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/">
   <env:Header/>
   <env:Body>
      <env:Fault>
         <faultcode xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/">ns1:Server</faultcode>
         <faultstring>JBWS024094: Authorization failed, principal=null</faultstring>
      </env:Fault>
   </env:Body>
</env:Envelope>
```

Am i doing something wrong or what could be the problem?

# Additional information
win32 x64 8.12.0

**Comment by deepakrkris** [comment]
@Swagnus can you try passing a header object to getServiceCatalogueList, strong-soap does not default header values like soap-ui.

Please take a look at [https://github.com/strongloop/strong-soap/blob/a2775deaa4e5e2d8c707cc7939861a778dfebf33/test/client-test.js#L317](url)

**Comment by deepakrkris** [comment]
@Swagnus were you able to modify the client and test this again ?

**Comment by Swagnus** [comment]
@deepakrkris Thank you for your reply!
I was able to add the headers i need to the request with the help of your link, thanks.

Now the problem is the body. As you can see in the example request from SoapUI `<v1:ServiceCatalogueListRequest/>` has been added automatically. 
Can this also be achieved automatically in strong-soap or do i have to add it manually?

**Comment by Swagnus** [comment]
Also i noticed that the `createClient` takes quite a while to execute, over 4 seconds. While the getServiceCatalogueList request takes about 200ms.
SoapUI executes the request in about 400ms.

What can be the cause of this?

**Comment by deepakrkris** [comment]
> Also i noticed that the `createClient` takes quite a while to execute, over 4 seconds. While the getServiceCatalogueList request takes about 200ms.
> SoapUI executes the request in about 400ms.
> 
> What can be the cause of this?

@Swagnus create client reads a remote/local wsdl , parses and adds the operations in the client. Depending on the size of the wsdl and schemas referred, it might take some time variably.

you can cache the client in app start up and avoid delays during a call.

**Comment by deepakrkris** [comment]
> @deepakrkris Thank you for your reply!
> I was able to add the headers i need to the request with the help of your link, thanks.
> 
> Now the problem is the body. As you can see in the example request from SoapUI `<v1:ServiceCatalogueListRequest/>` has been added automatically.
> Can this also be achieved automatically in strong-soap or do i have to add it manually?

@Swagnus you have to set the body fields explicitly as well, they are not defaulted.

**Comment by deepakrkris** [comment]
@Swagnus I am going to close this issue, and let you open new issues for additional questions.
