### ISSUE TITLE
Undefined result property in JSON format using SOAP web service

### ISSUE THREAD

**Issue by binx01** [strongloop/strong-soap#258]
According to the soap tutorial https://loopback.io/doc/en/lb4/soap-calculator-tutorial-run-and-test.html I have the issue with undefined response result in json format when using LB with our soap server.

Here is the soap server project https://github.com/binx01/soap-server-express-test/blob/master/index.ts for testing purposes simulating our original soap server (SOAP 1.1/RPC) Login response. Wsdl is the same as original but shortened.

Here is the loopback app https://github.com/binx01/soap-lb-api-test for testing purposes with soap datasource consuming the server response.

When debugging given response https://github.com/strongloop/strong-soap/blob/4d3522f6c546b1fda2c2d8c7c9dc81e4b6f87fea/src/client.js#L324-L341 parsing result is not successful because such key element Login is not expected.

1) Can you please help me to find out if given server response based on provided wsdl is right?
2) Soap envelope can return complex xml structures too, not just simple result value, is it intended to translate these structures to json object also or is it client responsibility to parse it itself?

Consulted with M.Bajtos to raise this issue. Thank you.

**Comment by deepakrkris** [comment]
@binx01 , there were some errors in your wsdl. I corrected them and the sample seems to work fine now.

Updated wsdl:
```
<definitions
    name="SoapServer"
    targetNamespace="urn:SoapServer"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="urn:SoapServer">

    <message name="LoginRequest">
        <part name="User" type="xsd:string"/>
        <part name="Password" type="xsd:string"/>
    </message>
    <message name="LoginResponse">
        <part name="result" type="xsd:string"/>
    </message>
    
    <portType name="SoapServer_PortType">
        <operation name="Login">
            <input message="tns:LoginRequest"/>
            <output message="tns:LoginResponse"/>
        </operation>
    </portType>

    <binding name="SoapServer_Binding" type="tns:SoapServer_PortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="Login">
            <soap:operation soapAction="urn:SoapServer#Login"/>
            <input>
                <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:SoapServer"/>
            </input>
            <output>
                <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:SoapServer"/>
            </output>
        </operation>        
    </binding>

    <service name="SoapService">
        <port name="SoapService_Port" binding="tns:SoapServer_Binding">
            <soap:address location="http://localhost:8000/login"/>
        </port>
    </service>
</definitions>
```

**Comment by deepakrkris** [comment]
@binx01 answers your questions:

**1. Can you please help me to find out if given server response based on provided wsdl is right?**
Corrected the wsdl file as in the previous comment and sample works fine now.

**2. Soap envelope can return complex xml structures too, not just simple result value, is it intended to translate these structures to json object also or is it client responsibility to parse it itself?**
strong-soap already handles complex xml structures. If you have troubles testing with typescript notations in loopback-next, please raise an issue in that repo.

**Comment by binx01** [comment]
@deepakrkris:
1. Solved, created own wsdl file according to your recommendation and provided it as local wsdl to datasource config and it works with original server too. Thank you!

2. Example of complex response copied from LB explorer without envelope part:

`{
  "result": {
    "SVMTEchoResult": {
      "value": "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\r\n<SVMTEchoResult>\r\n\t<serverName>Server</serverName>\r\n\t<databaseName>Database</databaseName>\r\n\t<date>2020-03-09T11:21:37.064</date>\r\n</SVMTEchoResult>"
    }
  }
}`

Value contains complex xml structure and can contain nested elements, it depends on the server's design, is it possible to configure (e.g. model, interface) the datasource to parse the value to JSON too? I tried to transform it with interceptor with success or it can handle client itself...just curious.

**Comment by deepakrkris** [comment]
@binx01 I also corrected the loopback soap service last time I tested, after changing the wsdl

```
import {getService} from '@loopback/service-proxy';
import {inject, Provider} from '@loopback/core';
import {SoapTestDataSource} from '../datasources';

export interface LoginResponse {
  result: {
    result: {
      $value: string
    }
  };
}

export interface LoginRequest {
  User: string;
  Password: string;
}

export interface SoapTestService {
  // this is where you define the Node.js methods that will be
  // mapped to REST/SOAP/gRPC operations as stated in the datasource
  // json file.
  login(args: LoginRequest): Promise<LoginResponse>;
}

export class SoapTestServiceProvider implements Provider<SoapTestService> {
  constructor(
    // soaptest must match the name property in the datasource json file
    @inject('datasources.soaptest')
    protected dataSource: SoapTestDataSource = new SoapTestDataSource(),
  ) {}

  value(): Promise<SoapTestService> {
    return getService(this.dataSource);
  }
}
```

**Comment by binx01** [comment]
@deepakrkris Thank you, updated affected sample projects, tested with no success, result still undefined.
