### ISSUE TITLE
Invalid protocol [ERR_INVALID_PROTOCOL]

### ISSUE THREAD

**Issue by dorcilio** [strongloop/strong-soap#259]
I am developing a service to make a SOAP request, but I am facing an error.

# Error
> TypeError [ERR_INVALID_PROTOCOL]: Protocol \"http:\" not supported. Expected \"https:\"
    at new ClientRequest (_http_client.js:119:11)
    at Object.request (http.js:42:10)

# Additional information
I don't know if the WebService changes from HTTPS to HTTP, but I needed this solution, in Java it works.

sorry for bad english...

# Description/Steps to reproduce
```
const URL = 'https://nfe.sefaz.go.gov.br/nfe/services/NFeConsultaProtocolo4?wsdl'
const privateKey = fs.readFileSync(privateKeyPath)
const publicKey = fs.readFileSync(publicKeyPath)
const password = ''
const wsSecurity = new soap.WSSecurityCert(privateKey, publicKey, password, 'utf8')

const options = {
  preserveWhitespace: false,
  disableCache: true,
  returnFault: true,
  forceSoap12Headers: true,
  wsdl_options: {
    forever: false,
    rejectUnauthorized: false,
    strictSSL: false,
    connection: 'keep-alive'
  }
}
soap.createClient(URL, options, (err, client) => {
  client.setSecurity(wsSecurity)
  const consSitNF = {
    consSitNFe: {
      attributes: {
        xmlns: 'http://www.portalfiscal.inf.br/nfe',
        versao: '4.00'
      },
      tpAmb: 1,
      xServ: 'CONSULTAR',
      chNFe: '52191231561298000132550010000077971157829350'
    }
  }
  client.nfeConsultaNFAsync(consSitNF).then(({ result, envelope, soapHeader }) => {
   ....
  }
})```

**Comment by raymondfeng** [comment]
Can you try to set `key` and `cert` in `wsdl_options`?

**Comment by deepakrkris** [comment]
@dorcilio the purpose of WSSecurityCert class is to add signed tokens to the soap payload, it is not meant for https transport, please see https://github.com/strongloop/strong-soap/blob/92239c41e2135eeab3c3ae0ec2e4f46253558945/test/ssl-test.js#L73
