### ISSUE TITLE
Cannot send a nil date element.

### ISSUE THREAD

**Issue by rsunbury** [strongloop/strong-soap#263]
# Description/Steps to reproduce
I am trying to send a null date to a nillable date field.  The problem that I am having, is that the check in xmlHandler.js to see if the field is nillable and if the value is null comes after calls where the value is converted to a date, and a null date ends up being 01-01-1970 so by the time it gets to the val check val is no longer null.

I tried to add the nil attributes to the element object, but if the value is undefined, when it tries to get converted to a date, an error is thrown.

# Expected result
If I pass DateofBirth = null as part of my request, I would expect:

 &lt;DateofBirth xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true" />

What I get is &lt;DateofBirth>1970-01-01&lt;/DateofBirth>

**Comment by raymondfeng** [comment]
@rsunbury In your WSDL/XSD, is `DateofBirth` element `nullable`?

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/strong-soap/blob/master/test/nillable-test.js

**Comment by rsunbury** [comment]
Yes it is,
<xsd:element maxOccurs="1" minOccurs="0" name="DateofBirth" nillable="true" type="xsd:date"/>

On the system that I am working with, pretty much all the dates are nullable.

**Comment by rsunbury** [comment]
I was playing around with this a bit, and came up with a piece of hack code that seems to fix this:

    if (descriptor instanceof ElementDescriptor) {
      name = descriptor.qname.name;
      let isSimple = descriptor.isSimple;
      if (isSimple && val === null && ['date', 'time', 'dateType'].indexOf(descriptor.type.name) > -1) descriptor.type.name = 'string';   //fix line

**Comment by dhmlau** [comment]
Closing as done as PR #265 has landed.
@rsunbury, thanks again for your contribution.
