### ISSUE TITLE
Socket hang up error

### ISSUE THREAD

**Issue by Diogoceiia** [strongloop/strong-soap#264]
I already tried everything and the error is always the same:

Error: socket hang up
    at connResetException (internal/errors.js:570:14)
    at Socket.socketOnEnd (_http_client.js:440:23)
    at Socket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ECONNRESET'
}

I'm consuming WSDL services from file, and this wsdl works well on soap UI testing tool.
I've been for a few days to try to resolve this :( 
Can you help me please?

**Comment by deepakrkris** [comment]
@Diogoceiia , can you please elaborate more on when the error is occurring?
Is it when connecting to the soap datasource ? 
Please upload the soap datasources configuration and also a sample of the wsdl and the connection code.

**Comment by Diogoceiia** [comment]
Hi @deepakrkris 
First of all, thank you for your answer.
I already found the problem. 
To found the problem, I used the fiddler as proxy and I was able to compare the requests between soap UI.
The problem was using incorrect soap headers.
BTW, I noticed that request package was deprecated and you are using it. You will replace it? Or will keep it?

Regards,
Diogo Carvalho

**Comment by deepakrkris** [comment]
if it is deprecated, we will soon replace it.
