### ISSUE TITLE
Default xmlns value not picked up

### ISSUE THREAD

**Issue by jonrober-80** [strongloop/strong-soap#267]
# Description/Steps to reproduce
Using strong-soap to parse a wsdl schema which sets the default xsd namespace `xmlns="http://www.w3.org/2001/XMLSchema"`, the type of an element is interpreted differently depending if the prefix `xsd:` is present before the type value. In the following schema:
```
    <schema elementFormDefault="qualified" targetNamespace="http://example.com/wsdl/myAPI" version="1.0" xmlns="http://www.w3.org/2001/XMLSchema">
      <element name="RetrieveRequestMsg">
        <complexType>
          <sequence>
            <element name="StringXsd" type="xsd:string" minOccurs="1" maxOccurs="1" />
            <element name="StringDefault" type="string" minOccurs="1" maxOccurs="1" />
          </sequence>
        </complexType>
      </element>
    </schema>
```
I would expect that `xsd:string` and `string` should both result in the simple type of `string`, as without the `xsd` namespace the default namespace will be used, which in this case is the XMLSchema one. 

In practice after calling `operation.describe(def)` the element with the type `xsd:string` has the value `isSimple=true` and `type` has QName value of:
``` 
{
  "nsURI": "http://www.w3.org/2001/XMLSchema",
  "name": "string"
} 
```
The element with the type of `string` has the values `element.isSimple=false` and `type=undefined`

There is a wsdl and a test which demonstrate this in branch https://github.com/jonrober-80/strong-soap/tree/defaultNS

# Link to reproduction sandbox

See branch https://github.com/jonrober-80/strong-soap/tree/defaultNS

# Expected result

I would expect the element with the type `string` to contain the same type information as the element not using the short hand and setting type to `xsd:string`

# Acceptance Criteria
- [ ] fix: find out why the value is not populated

**Comment by deepakrkris** [comment]
@jonrober-80 I am able to recreate the error with your tests, thanks. marking this as a bug.

**Comment by dextherry** [comment]
this is happening to me too, prefix of attributes are removed :O
