### ISSUE TITLE
Proposal: always return an array for response element where maxOccurs > 1

### ISSUE THREAD

**Issue by LoneRifle** [strongloop/strong-soap#268]
Currently, strong-soap inherits node-soap's behaviour of returning the following for a given element defined as:
```xml
<xs:sequence>
  <xs:element maxOccurs="(greater than 1)" />
</xs:sequence>
```
this behaviour returns such an element as an object if it occurs once, or an array of objects if more than once. This complicates the handling of the response, as we now have to determine whether the element being returned is a single object or an array of objects. 

Given the definition of such elements, we already expect the number of occurrences to be greater than 1. I hence propose that strong-soap should _always return an array of objects_ for such elements, so that response handlers can be simplified.

Desired behaviour can be inferred from vpulim/node-soap#1100

**Comment by deepakrkris** [comment]
@LoneRifle the client can always make necessary checks to see if a returned element is an array. So why force to return an array always ? this could break existing clients.

**Comment by LoneRifle** [comment]
How would this break existing clients? Those clients would already embed logic to receive and handle either a single object or an array of objects due to the arguably inconsistent nature of what is being returned. I am unsure why a client would break trying to handle a one-item array

**Comment by deepakrkris** [comment]
@raymondfeng can you validate this requirement and the associated PR. They look good to me.
