### ISSUE TITLE
Server support

### ISSUE THREAD

**Issue by chegzo** [strongloop/strong-soap#274]
The readme mentions the server part is a "mock-up". 
Is there any reason not to use it as a regular server with loopback4? Are there any limitations / missing features?

**Comment by deepakrkris** [comment]
@chegzo IMO strong-soap can listen, parse soap requests and send back soap response, but certain soap validations must be handled by the developer . In other words our soap server is not a strict soap interface.

**Comment by deepakrkris** [comment]
@chegzo , hope my answer clarified your doubts, closing this issue now.
