### ISSUE TITLE
How to add attribute in element in body xml

### ISSUE THREAD

**Issue by dextherry** [strongloop/strong-soap#279]
# Description/Steps to reproduce

currently I have this:

```
var args = {
  params:{
    email:'myemail@mail.com'
  }
}
client.myfunction(args, function(err, result) {
...
})

```

and it generates this xml body:
```
...
<params>
  <email>myemail@mail.com</email>
</params>
...
```

# Expected result
I want to generate this structure, with attributes in the elements, but I can not, how can achieve this?:

```
...
<params SOAP-ENC:arrayType="ns2:Map[1]" xsi:type="SOAP-ENC:Array">
  <email xsi:type="ns2:Map">myemail@mail.com</email>
</params>
...

```

# Additional information
maybe it is a incorrect structure, but the point of the issue is that I would like to know how to add attributes in the elements into the body of the generated xml
Thanks

**Comment by raymondfeng** [comment]
Use `$attributes` in json to contain attribute name/value as an object.

**Comment by dextherry** [comment]
that works! thanks dear staff
I also noticed that I need to leave empty the options for createClient and `$attributes` works

just a help more please, can you help me with issue [278](https://github.com/strongloop/strong-soap/issues/278) please?
Thanks

**Comment by dhmlau** [comment]
Closing as resolved.
