### ISSUE TITLE
`forceSoapVersion` should be documented

### ISSUE THREAD

**Issue by silverwind** [strongloop/strong-soap#281]
https://github.com/strongloop/strong-soap/pull/56 added the WDSL option `forceSoapVersion`, but it's nowhere to be found in `README.md` and I had to dig into the source code to find it. Suggesting to add some documentation for it.

**Comment by dhmlau** [comment]
@silverwind, thanks for your suggestion. Would you like to submit a PR for the docs? Thanks.

**Comment by silverwind** [comment]
All it does seem to do is set a different [`soapNsURI` and `Content-Type`](https://github.com/strongloop/strong-soap/blob/d8b806f7b727b26bf217cf201926af6e8684638d/src/client.js#L134-L137) if the [detected version](https://github.com/strongloop/strong-soap/blob/a2775deaa4e5e2d8c707cc7939861a778dfebf33/src/parser/wsdl/operation.js#L52-L58) is different than 1.2.

I don't nearly understand enough of this stuff, but I know had to set it to a different value than `1.2` to prevent a `VersionMismatch` from a Apache Axis2 service.

I do think it may be better to just expose `soapNsURI` and `Content-Type`
