### ISSUE TITLE
XSD Group Element doesn't accept minOccurs and maxOccurs

### ISSUE THREAD

**Issue by sgabriel** [strongloop/strong-soap#282]
# Description/Steps to reproduce
`<xs:group>` elements can't be used multiple times even if defined with `maxOccurs="unbounded"` in WSDL. 
https://github.com/strongloop/strong-soap/blob/ef76e7ee3bc004f5a481d01582feb87cf6c53f9c/src/parser/typeRegistry.js#L34
This comment suggest that group doesn't check for `maxOccurs` and `minOccurs` attributes. 
This leads to the behaviour, that on jsonToXml generation arrays aren't accepted for groups.

# Additional information
https://www.w3schools.com/xml/el_group.asp

**Comment by emonddr** [comment]
@sgabriel , please elaborate. How does the comment suggest it doesn't handle max or min Occurs?

Please provide a minimal application to demonstrate the issue to help problem resolution. Thank you. :)

**Comment by sgabriel** [comment]
I will try to provide a "request-response-sample" via PR or should I just add code snippets to this issue?

**Comment by sgabriel** [comment]
I added a Test-Case here: https://github.com/sgabriel/strong-soap/commit/ea54b54b7319f8eed947bd953d237d60908a3760
