### ISSUE TITLE
WSDL not opening correctly

### ISSUE THREAD

**Issue by wbailey-jb** [strongloop/strong-soap#283]
# Description/Steps to reproduce
WSDL URL: https://uat.contigocloud.com/enTrader/WestGass/WCFServices/TradingService.svc?wsdl

WSDL can be opened by SoapUi 5.5 but not strong-soap. When importing schemas, I see the error "Document/literal part should use element".

Open the linked WSDL.
# Link to reproduction sandbox
I was just using the base branch.

# Expected result
WSDL loads properly

error "Document/literal part should use element"
# Additional information

**Comment by wbailey-jb** [comment]
Has anyone seen this?

**Comment by raymondfeng** [comment]
@wbailey-jb Please use `DEBUG=strong-soap:wsdl strong-soap:wsdl:include` env var to run your app. It will print out information about wsdl/xsd loading.

**Comment by wbailey-jb** [comment]
I believe the issue is that this particular WSDL has an import for another WSDL. If I copy the contents of the second WSDL into the original file it loads properly.

**Comment by wbailey-jb** [comment]
Here are the WSDL logs from using the env var you suggested.
[strong-soap-log.txt](https://github.com/strongloop/strong-soap/files/4691661/strong-soap-log.txt)

**Comment by raymondfeng** [comment]
Hmm, the wsdl itself seems to have the same `targetNamespace` (http://entrader.contigoenergy.com/Contigo.Entrader.Service) as the 1st imported xsd. Maybe it confuses the resolution.

**Comment by raymondfeng** [comment]
I'm not sure if it has something to do with https://github.com/strongloop/strong-soap/blob/master/src/parser/wsdl.js#L237.

**Comment by wbailey-jb** [comment]
So i'm not sure if its because of the xsd import because if I remove the import I still end up with the same error. I believe it has something to do with the fact that the initial wsdl has an import for a second wsdl which has an import for the first wsdl, ect... Is there any form of check for circular imports currently?

**Comment by wbailey-jb** [comment]
Hi @raymondfeng I created a reduced wsdl that still shows the issue.

[reduced.txt](https://github.com/strongloop/strong-soap/files/4719616/reduced.txt)
(had to rename it to a .txt because github wouldn't allow me to upload a .wsdl)
