### ISSUE TITLE
Remove GPL License from upstream dependencies

### ISSUE THREAD

**Issue by michaelfarrell76** [strongloop/strong-soap#285]
# Description/Steps to reproduce

- Add strong-soap@2.0.0 to your package.json
- Run check using [fossa](https://fossa.com/) to search for GPL licenses in package tree
- Get an alert for strong-soap that looks like the following:

<img width="578" alt="Screen Shot 2020-06-03 at 11 48 43 AM" src="https://user-images.githubusercontent.com/10264973/83676854-2dc54c80-a590-11ea-87c2-4d2f2cfd0a43.png">

# Link to reproduction sandbox

Given that this is a license thing, I'd prefer to provide the full solution below instead of creating a reproduction sandbox

# Expected result

There should be no GPL licenses in any of the packages that this module consumes

# Additional information

I've dug deep into the dependency chain and I think most of the upstream changes have been made already.

- At the root, `adm-zip` is the issue. This package has been updated to remove GPL code and any version above `0.4.12` no longer has this warning.
- `cldr-data-downloader` is the next culprit any looking at version [`0.3.5`](https://github.com/rxaviers/cldr-data-downloader/blob/master/package.json#L3) now has `adm-zip` at `0.4.13` and so this package is no longer an issue
- Next level is [`cldr-data`](https://github.com/rxaviers/cldr-data-npm/blob/master/package.json#L39) which currently pings to 0.3.x of `cldr-data`, so it is unclear to me whether this package has been published with a more recent version with the bumped `adm-zip`. I've [opened an issue](https://github.com/rxaviers/cldr-data-npm/issues/67) in the `cldr-data` package asking them to bump this version in case it has not already been bumped.
- Next is the `globalize` package that relies on `cldr-data` and `cldr-data-downloader`. I've [opened an issue](https://github.com/globalizejs/globalize/issues/900) here to ask them to bump these versions
- Then `strong-globalize` needs to be updated to point to the new `globalize` package. I've [opened an issue](https://github.com/strongloop/strong-globalize/issues/164) for this as well
- Finally this package needs to be updated to point to the latest version of globalized and republished

**Comment by raymondfeng** [comment]
There is no runtime dependency on `adm-zip`. See:
```
npm ls adm-zip
strong-soap@2.0.0 /Users/rfeng/Projects/loopback3/strong-soap
└── (empty)

```
