### ISSUE TITLE
Is there any way to override the namespace?

### ISSUE THREAD

**Issue by Guatom** [strongloop/strong-soap#30]
Hey! Good afternoon. I'm almost there to get the client working! The only issue I'm having is that the namespace for the body RQ is not the right one. Is there any way to override it?

I think there has to be a way for strong-soap to get the proper namespace though, since SOAPUI gets it OK. strong-soap is way better than soap-node anyway: strong-soap understands very well which nodes require namespace and which don't.

Would it be useful if I sent the wsdl?

A million thanks in advance.

**Comment by rashmihunt** [comment]
Please attach the testcase with the wsdl.

**Comment by Guatom** [comment]
Close this issue as I'm quite close to solving it in the code; It's just a minor thing, I think I can send a PR. What's the channel for talking about PRs? I read in contributing that I should talk to developers before submitting a PR and I'd like to talk to anyo of them

**Comment by Guatom** [comment]
Wrote a PR.
