### ISSUE TITLE
Revisit a test case in wsdl-test.js

### ISSUE THREAD

**Issue by rashmihunt** [strongloop/strong-soap#41]
Revisit this test - 'should get the parent namespace when parent namespace is empty string' in https://github.com/strongloop/strong-soap/blob/master/test/wsdl-test.js

1) The test doesn't seem to be testing anything - checking client request or response
2) Noticed a CI failure due to this test - check for missing done() method in the logic.

**Comment by superkhau** [comment]
CI is passing ATM. Will create new issue if necessary.
