### ISSUE TITLE
Response not properly mapped

### ISSUE THREAD

**Issue by fdrx** [strongloop/strong-soap#46]
I am testing strong-soap and facing a "Uncaught error: Cannot read property 'qname' of undefined" when getting the following response:

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <MemberGetProfileResponse ExceptionCode="0" LoginId="abc@gmail.com" MemberType="20" FamilyName="abc" FirstName="test" Birthday="19840101" Gender="1" Zipcode="0010013" AddressPrefecture="北海道" AddressCityTown="札幌市北区 北十三条西）" AddressHouse="" TelephoneNumber1="00000000000" Email="abc@gmail.com" FamilyNameFurigana="" FirstNameFurigana="" Language="" ConsumerType="" Referable="false" CounterReferals="0" CounterRemainingReferrals="0" OptInEmail="1" OptInDM="1" IsDraft="false" UserSequence="0000001" xmlns="http://www.b-i.com/ns/LoyaltyWebservice/"/>
   </s:Body>
</s:Envelope>
```

I have fixed that by editing the client.js file line 304 this way:

```
        //result = obj.Body[outputBodyDescriptor.elements[0].qname.name];
        var resultContainer = outputBodyDescriptor.elements[0] || outputBodyDescriptor;
        result = obj.Body[resultContainer.qname.name];
```

**Comment by ritch** [comment]
@fdrx do you mind submitting your suggested fix as a PR?

**Comment by fdrx** [comment]
done

**Comment by rashmihunt** [comment]
@fdrx  In client.js on the master branch code, prior to the line
  result = obj.Body[outputBodyDescriptor.elements[0].qname.name]; 
there is a check for elements length in outputBodyDescriptor

https://github.com/strongloop/strong-soap/blob/master/src/client.js#L314

if (outputBodyDescriptor.elements.length) {   result = obj.Body[outputBodyDescriptor.elements[0].qname.name]; }

Above check should avoid the problem you are seeing. Can you please test your use case on the latest master branch code and let us know if it resolved your issue? If your problem still persists with master branch code, please send your WSDL.

**Comment by rashmihunt** [comment]
@fdrx let me know if my above explanation fixed your issue. We would like to close this issue.

**Comment by rashmihunt** [comment]
@fdrx closing the issue since the code has the fix as per my explanation above. If problem persists, please reopen.

**Comment by fdrx** [comment]
thank you, very sorry for the dela
