### ISSUE TITLE
Please add use of obj to parameters for requesting info

### ISSUE THREAD

**Issue by JasonScopServ** [strongloop/strong-soap#48]
In my case I'm requesting info from a soap server, like this below...

```js
var requestArgs = {
  authUserName: 'user',
  authPassword: 'pass',
  username: 'user',
  requestedValues: {
      string: 'userid',
      string: 'Email',
      string: 'DisplayName'
  }
};
```

But it seems that the result is only returning the last index of the obj in requestedValues (DisplayName), It does not seem to run through the obj when making the xml request. Please let me know if maybe I'm
doing this wrong or if it is not actually implemented yet.

Thanks.

**Comment by ritch** [comment]
This doesn't seem related to `strong-soap`. Look at your object...

```
> var requestArgs = {
  authUserName: 'user',
  authPassword: 'pass',
  username: 'user',
  requestedValues: {
      string: 'userid',
      string: 'Email',
      string: 'DisplayName'
  }
};

> requestArgs.requestedValues
{ string: 'DisplayName' }
```
