### ISSUE TITLE
Look into upgrading node-uuid

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-soap#50]
Should we use `uuid` instead of `node-uuid`?

**Comment by rashmihunt** [comment]
@ritch We should. I had triaged a community PR which switched to uuid and I was planning to land the PR this week. But I no longer see it now and it's not merged either. I can switch to uuid as part of this issue.

**Comment by rashmihunt** [comment]
@ritch Fixed as part of PR https://github.com/strongloop/strong-soap/pull/52

**Comment by ritch** [comment]
@rashmihunt can we close this now?

**Comment by rashmihunt** [comment]
@ritch I am closing this issue since I fixed it as part of PR https://github.com/strongloop/strong-soap/pull/52
