### ISSUE TITLE
Use XSD schema rules

### ISSUE THREAD

**Issue by EntityB** [strongloop/strong-soap#53]
One of the biggest issue of [node-soap](https://github.com/vpulim/node-soap) and [strong-soap](https://github.com/strongloop/strong-soap) libs is it doesn't follow XSD schema at all. 

Current implementation of strong-soap just passing data as JSON to [xmlbuilder-js](https://github.com/oozcitak/xmlbuilder-js) lib. Unfortunately `xmlbuilder-js` doesn't provide any functionality to read and handle XSD schema. On the other hand, `strong-soap` [seems to be able to read and parse schema](https://github.com/strongloop/strong-soap/tree/master/src/parser/xsd). 

What is happening now
When `strong-soap` receives JSON object/XML data, it iterates thru it and build XML (via `xmlbuilder-js`)/JSON.

Causes
- XML request and response might **contain elements and structures that are not part of XSD**. 
- **Wrong order** of sequences, extensions and complex elements.
- Values might not be valid according to XSD.
These causes makes both libraries unusable in many cases. 

What it should do
When `strong-soap` receive JSON object/XML data, it should iterate thru XSD schema object and do custom mapping to build XML from received JSON object/build JSON from received XML.

**Comment by EntityB** [comment]
It made me to do (very very very poor) implementation that is handling at least the wrong order of elements and strips elements and structures that are not part of XSD. 

I [passed parsed XSD from strong-soap to xmlbuilder-js](https://github.com/EntityB/strong-soap). And then I made [small branch in code of xmlbuilder-js](https://github.com/EntityB/xmlbuilder-js) that can assemble XML following XSD rules. (+I didn't write in coffee script)

Anyway my solution is super ugly and I'm pretty sure it doesn't cover many possible scenarios of XSD schema structures. If someone need it desperately, you can use it.

**Comment by bgdavidx** [comment]
I fixed the ordering of xsd elements without needing to fork xmlbuilder: https://github.com/TeamO3/strong-soap/commit/dd313e88e6c036fcfd0c89fbda88d1b79a4d6436

Hope this helps someone.

**Comment by raymondfeng** [comment]
@bgdavidx Would you like to submit a pull request?

**Comment by bgdavidx** [comment]
@raymondfeng sure, here you go: https://github.com/strongloop/strong-soap/pull/98
