### ISSUE TITLE
Getting InvalidSecurity faultstring when calling WCF web service

### ISSUE THREAD

**Issue by farhoud** [strongloop/strong-soap#57]
Hi,

I need to call a WCF service, I have a username and password, searching on the web it appears I need to use WS-Security. Here's my code:
```javascript
var soap = require('strong-soap').soap;
var url = '<addr>/Common.svc?wsdl';
var requestArgs = {
    arg: 'value'
};
var options = {};

soap.createClient(url, options, function(err, client) {
    client.setSecurity(new soap.WSSecurity('<username>', '<password>'));
    client['<api>'](requestArgs, function(err, result, envelope) {
        cosole.log(err);
        console.log(JSON.stringify(result));
    });
});

```
And I'm getting the same error as not setting security:
```
Error: faultcode: a:InvalidSecurity faultstring: An error occurred when verifying security for the message.
    at XMLHandler.xmlToJson (/node_modules/strong-soap/src/parser/xmlHandler.js:626:23)
```
Any advice is very much appreciated.

**Comment by rashmihunt** [comment]
@farhoud Can you check your WCF service and see what type of security it uses and try to pass that type of security through client.setSecurity(..) method? I am not familiar with WCF service. Quick search of web shows the difference between web service and WCF https://www.codeproject.com/Articles/139787/What-s-the-Difference-between-WCF-and-Web-Services 

I don't see what type security it needs though. I am guessing it depends on the WCF service in question. Adding @raymondfeng to this thread. @raymondfeng any pointers?

**Comment by farhoud** [comment]
Thank for replay the message is not human friendly but service provider send us wrong account information and they have firewall protected service . so everything was wrong.
strong soap works fine

**Comment by rashmihunt** [comment]
Closing this as this is not a problem with strong-soap as per above comments.
