### ISSUE TITLE
Feature proposal: Soap Headers should be at request level and not at client level

### ISSUE THREAD

**Issue by Guatom** [strongloop/strong-soap#59]
Hey!

I'd like to suggest, and code if approved, a feature for moving header handling from the client to the request. Actually for setting a header, the methods `addSoapHeader` or `changeSoapHeader` have to be used. These methods modify the client. Considering that, if the invoked web services use the headers for specifying session or technical data, each time a web service is invoked, the client has to be modified to specify the new values of the headers.

I really think the headers of the request should work exactly as the body of the request: they should be specified request by request, and the client should remain the same no matter what the request has.

As an example, I use several web services from Sabre, and they look like the following one:

http://webservices.sabre.com/wsdl/tpfc/OTA_AirAvailLLS2.3.0RQ.wsdl

If you use SOAPUI to create a request for that WSDL, you'll see that it has a very big header and most of its data changes dynamically from request to request, so modifying the client for each request wouldn't be the best option.

Please let me know if something like this would be accepted.

A million thanks in advance.

**Comment by rashmihunt** [comment]
Copying @raymondfeng for this one

**Comment by benfoxall** [comment]
It's possible to do this with the `security` client option:

```js
let secret
client.setSecurity({
   addOptions: (options) => secret = options.secret,
   addSoapHeaders: xml => {
      if(secret) {
        // modify header here
      }
      return xml
   }
})


// when making a request:
client.yourRequestHere({...}, {secret: 'REQUEST_SECRET'})
```

I've spent quite a while looking through the relevant code in [client.js](https://github.com/strongloop/strong-soap/blob/master/src/client.js#L170-L188) - and I'm fairly sure that this is safe.

I think it would feel a bit nicer if `security.addSoapHeaders` received the request options as well as the header.  I'd be happy to raise a PR if that's useful/correct.

**Comment by Guatom** [comment]
Hey @benfoxall! Thanks for your reply.

It looks like you're totally right! If I understood correctly, the headers would be added to the envelope after the envelope is created (line 187), so the client remains the same. Great catch.

So far we've been using `changeSoapHeader` and that hasn't caused troubles so far. If any problem appears, we'll definitively move to what you said or something cleaner if something appears.

Thanks a lot!
