### ISSUE TITLE
Allow security to be set for the initial request

### ISSUE THREAD

**Issue by joshlevinson** [strongloop/strong-soap#62]
Hi there!

I'm in a situation where a WSDL is 100% protected–even from the initial request–by WSSecurityCert. I'm finding that `strong-soap` only allows one to set the security of the client after it's been created, meaning that the initial "discovery" request is unsecured (and thus gets blocked).
Any advice on securing the initial wsdl request?

Thanks for this lib; it's very useful!

**Comment by rashmihunt** [comment]
Only the new NTLMSecurity support in this module, supports authentication for getting the WSDL (http 'GET') at the moment. We should support this for other security similar to what we have done for NTLMSecurity.

**Comment by barrettc** [comment]
I'm encountering the exact same scenario here -- I need to set security before the client can be created.
