### ISSUE TITLE
Clarification on custom namespaces

### ISSUE THREAD

**Issue by joshlevinson** [strongloop/strong-soap#63]
Using the attached wsdl, I'm unable to get the correct namespaces going.
I'm making a request like:

```javascript
client.GetClasses({
    'GetClassesRequest': {
      'PageInfo': {
        'Page' : 2,
        'PageSize': 1,
      }
    }
  }
```

The request is successful, but `PageInfo`, `Page`, and `PageSize` should all have the `req:` namespace; instead, they no namespace at all.
The request XML looks like:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <x509Thumbprint xmlns="http://JonasFitness.com/CompeteDataService/2013/04/01">REDACTED</x509Thumbprint>
    <CompanyID xmlns="http://JonasFitness.com/CompeteDataService/2013/04/01">REDACTED</CompanyID>
  </soap:Header>
  <soap:Body>
    <ns1:GetClasses xmlns:ns1="http://JonasFitness.com/CompeteDataService/v2_0/ClassService">
      <ns1:GetClassesRequest>
        <!--WRONG PART HERE-->
        <PageInfo>
          <Page>2</Page>
          <PageSize>1</PageSize>
        </PageInfo>
        <!--END WRONG PART-->
      </ns1:GetClassesRequest>
    </ns1:GetClasses>
  </soap:Body>
</soap:Envelope>
```

I'm also confused why the other namespace definitions aren't added to the envelope. Those should be:
xmlns:clas="http://JonasFitness.com/CompeteDataService/v2_0/ClassService"
xmlns:req="http://JonasFitness.com/CompeteDataService/v2_0/Requests"
xmlns:com="http://JonasFitness.com/CompeteDataService/v2_0/Common"

My questions are:

1. How do I add custom namespace definitions to the envelope? I assumed those would get added by consumption of the wsdl.
2. How do I ensure the correct namespaces are used for the specified tags?

I reviewed all the tests of this repo to try to find this info myself, but everything appears to "just work" via consumption of the wsdls (e.g. [this one](https://github.com/strongloop/strong-soap/blob/master/test/request-response-samples/Dummy__should_work_with_imported_schemas/request.xml) that has custom `n` and `c` namespaces).

[ClassService.svc.txt](https://github.com/strongloop/strong-soap/files/657634/ClassService.svc.txt) (note GH didn't let me upload an XML, so I renamed this to a txt file)

**Comment by joshlevinson** [comment]
Closing this out, as this worked for me all of the sudden.

**Comment by Gamaroff** [comment]
This problem has happened to me.
When I look at the Request Body it looks like this:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ns1:MyMethod xmlns:ns1="http://webServices/">
      <param1>1.0</param1>
      <param2>Peaches</param2>
    </ns1:MyMethod>
  </soap:Body>
</soap:Envelope>
```

The  \<request\> tag is missing. Ie it should look like this:

~~~~
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ns1:MyMethod xmlns:ns1="http://webServices/">
      <request>
        <param1>1.0</param1>
        <param2>Peaches</param1>
      </request>
    </ns1:MyMethod>
  </soap:Body>
</soap:Envelope>
~~~~

The call fails because of this. How do I get the \<request\> tag back in there?

**Comment by jampy** [comment]
@Gamaroff did you find a solution?

**Comment by Gamaroff** [comment]
Unfortunately not.

**Comment by Gamaroff** [comment]
Yes I did. I will dig up the code.

**Comment by Gamaroff** [comment]
When passing in the args I added a nested Request tag:

```
var args = {
 request : {
  name         : 'Denzel',
  last_name        : 'Washington'
 }
};
```

**Comment by jampy** [comment]
@Gamaroff: sorry, I thought you had the same problem regarding the namespace

@joshlevinson: I'm having the exact same problem as you describe but unfortunately it does not "work all of the sudden". What version of `strong-soap` are you using?

**Comment by joshlevinson** [comment]
@jampy Unfortunately, I don't have access to the project I was working on anymore :/

**Comment by jampy** [comment]
@joshlevinson: no problem. I switched to a custom SOAP client in the meantime. It was rather easy in the end and took less time than I already spent trying to get any of the node-soap libs to work :-)
