### ISSUE TITLE
add to apidocs.strongloop.com

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-soap#64]
<img width="533" alt="screen shot 2016-12-16 at 12 17 09 pm" src="https://cloud.githubusercontent.com/assets/462228/21277184/dd8330d4-c389-11e6-819e-d50966a5432a.png">

# 😢

**Comment by ritch** [comment]
@raymondfeng @rashmihunt @crandmck @siddhipai

**Comment by crandmck** [comment]
I can do this when I address https://github.com/strongloop-internal/apidocs.strongloop.com/issues/67

**Comment by crandmck** [comment]
@ritch Should we also add https://github.com/strongloop/loopback-connector-soap to API docs?

**Comment by crandmck** [comment]
@rashmihunt Let's discuss.
