### ISSUE TITLE
What happended to overrideRootElement?

### ISSUE THREAD

**Issue by penrillian-chrisa** [strongloop/strong-soap#68]
The overrideRootElement option seems to have been removed. Is there an alternative way of changing the soap:body to include nested elements?

Instead of:
```
  const requestArgs = {
    customer: 123
  }
```
having:
```
  <soap:Body>
    <customer>123</customer>
  </soap:Body>
```
I want the body to have:
```
  <soap:Body>
    <method>
      <request>
        <customer>123</customer>
      </request>
    </method>
  </soap:Body>
```

**Comment by rashmihunt** [comment]
@penrillian-chrisa strong-soap code strictly follows WSDL/XSD schema. method, request and customer in your above example has to be defined in WSDL/XSD  

Will be closing this - as working as expected

**Comment by rashmihunt** [comment]
Closing this issue as per above clarification.
