### ISSUE TITLE
Missing Request Tag in Method

### ISSUE THREAD

**Issue by Gamaroff** [strongloop/strong-soap#75]
When I look at the Request Body it looks like this:
~~~~
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ns1:MyMethod xmlns:ns1="http://webServices/">
      <param1>1.0</param1>
      <param2>Peaches</param2>
    </ns1:MyMethod>
  </soap:Body>
</soap:Envelope>
~~~~
The \<request\> tag is missing. Ie it should look like this:

~~~~
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ns1:MyMethod xmlns:ns1="http://webServices/">
      <request>
        <param1>1.0</param1>
        <param2>Peaches</param1>
      </request>
    </ns1:MyMethod>
  </soap:Body>
</soap:Envelope>
~~~~
The call fails because of this. How do I get the \<request\> tag back in there?

**Comment by rashmihunt** [comment]
@Gamaroff Can you attach your WSDL and java script (or just code snippet) where you trying invoke "MyMethod" Web Service operation?

**Comment by Gamaroff** [comment]
Hi @rashmihunt thanks for the help.

The url endpoint is: https://webservices.compuscan.co.za/NormalSearchService?wsdl

My code is as follows:

```
var soap = require('strong-soap').soap;
var url = 'https://webservices.compuscan.co.za/NormalSearchService?wsdl';

var args = {
	...
};

soap.createClient(url, function (err, client) {

	client.DoNormalEnquiry(args, function (err, result, envelope) {
			
	});
});

```

**Comment by rashmihunt** [comment]
@Gamaroff  I don't see MyMethod, param1 and param2 from above request defined in WSDL/XSD and it should be defined in the schema.  Your input JSON seems incorrect.  You can refer to example under https://github.com/strongloop/strong-soap/blob/master/example/stockquote.js or mocha tests under https://github.com/strongloop/strong-soap/tree/master/test Look at server-client-document-test.js or server-client-rpc-test.js etc

For DoNormalEnquiry operation you are using, as per your WSDL/schema, the input JSON should be 
```
var args = {
  request: {
    pUsrnme: 'testuser',
    pPasswrd: 'testpass',
    pVersion: 'testVer',
    pOrigin: 'testOrigin',
    pOrigin_Version: 'testOrigin_Version',
    pInput_Format: 'pInput_Format',
    pTransaction: 'pTransaction'
  }
};

```

The generated request envelope with the current code is, 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header/>
  <soap:Body>
    <ns1:DoNormalEnquiry xmlns:ns1="http://webServices/">
      <request>
        <pUsrnme>testuser</pUsrnme>
        <pPasswrd>testpass</pPasswrd>
        <pVersion>testVer</pVersion>
        <pOrigin>testOrigin</pOrigin>
        <pOrigin_Version>testOrigin_Version</pOrigin_Version>
        <pInput_Format>pInput_Format</pInput_Format>
        <pTransaction>pTransaction</pTransaction>
      </request>
    </ns1:DoNormalEnquiry>
  </soap:Body>
</soap:Envelope>
```

I will be closing this issue - working as expected.

**Comment by rashmihunt** [comment]
closing - working as expected. See above comment.

**Comment by Gamaroff** [comment]
Thank you. Everything works as expected.
I appreciate the help.
