### ISSUE TITLE
How do I get these extra headers

### ISSUE THREAD

**Issue by LucasBrazi06** [strongloop/strong-soap#84]
Dear developpers,

I do not manage to add the extra headers of soap namespace 'addressing' (see below).

**Request that works:**
```
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing">
  **<s:Header>
    **<a:Action s:mustUnderstand="1">/Reset</a:Action>**
    <h:chargeBoxIdentity xmlns:h="urn://Ocpp/Cp/2010/08/" xmlns="urn://Ocpp/Cp/2010/08/">EV_CHARGER_4</h:chargeBoxIdentity>
    <a:From>
      <a:Address>http://localhost/CentralSystemService12</a:Address>
    </a:From>
    <a:MessageID>urn:uuid:e540992d-e4d2-4fbe-9325-490c87fe4691</a:MessageID>
    <a:ReplyTo>
      <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
    </a:ReplyTo>
    <a:To s:mustUnderstand="1">http://127.0.0.1:8081/ChargeBox/Ocpp</a:To>
  </s:Header>**
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <resetRequest xmlns="urn://Ocpp/Cp/2010/08/">
      <type>Hard</type>
    </resetRequest>
  </s:Body>
</s:Envelope>
```

**Request with strong-soap**
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:Header/>
  <soap:Body>
    <ns1:resetRequest xmlns:ns1="urn://Ocpp/Cp/2010/08/">
      <ns1:type>Hard</ns1:type>
    </ns1:resetRequest>
  </soap:Body>
</soap:Envelope>
```

**The Code**
```
      // Create client
      var options = {};
      var requestArgs = {
        resetRequest: {
          type : "Hard"
        }
      };
      var requestHeader = {
        action: {
          type : "Reset"
        }
      };
      soap.createClient(chargingStationWdsl12URL, options, function(err, client) {
        client.on("request", function(request) {
          console.log(request);
        });
        // client.setEndpoint("http://127.0.0.1:8081/ChargeBox/Ocpp");
        client.Reset(requestArgs, function(err, result, envelope) {
          console.log(err.message+"\n\n");
          console.log(JSON.stringify(result));
        }, null, requestHeader);
      }, "http://127.0.0.1:8081/ChargeBox/Ocpp");

```

Thanks for your help in advance.

Best regards,
Serge.

**Comment by rashmihunt** [comment]
@LucasBrazi06 You can use client.addSoapHeader(value).. See example in this test https://github.com/strongloop/strong-soap/blob/master/test/server-test.js  Search for '<Security>'

**Comment by aymen-mouelhi** [comment]
@rashmihunt I have the same issue.
client.addSoapHeader(value) creates a header correctly, but the problem happens when you have a set of headers that have the same namespace, how can you assign a namespace to the whole soap enveloppe?

**Comment by LucasBrazi06** [comment]
@rashmihunt

Moreover the addSoapHeader() works with XML form but not with JSon:

JSon do not Work as it's checked against the WSDL:
client.addSoapHeader({ Action: '/Reset'}, {name: 'addr', nsURI: 'http://www.w3.org/2005/08/addressing'});

The XML works and is straightforward (no check done) but the soap envelope is missing
client.addSoapHeader('<addr:Action>/Reset</addr:Action>');

Thanks for your support!

Cheers,
Serge.

**Comment by LucasBrazi06** [comment]
We now pass the namespace at tag level instead at document level which is less efficient but it works.

**Comment by yipiha** [comment]
Is it possible to add a namespace to the whole envelope (i.e., in the soap:Envelope tag) or not?
