### ISSUE TITLE
Complex data

### ISSUE THREAD

**Issue by fdabrao** [strongloop/strong-soap#87]
Hello all,

How do I configure something like this:

``<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wrap="http://wrappers.webservice.appservices.core.inteqnet.com" xmlns:xsd="http://beans.webservice.appservices.core.inteqnet.com/xsd">
   <soapenv:Header/>
   <soapenv:Body>
      <wrap:getSQLQueryResults>
         <wrap:credentials>
            <xsd:userName>xxxxxx</xsd:userName>
            <xsd:userPassword>xxxxxx</xsd:userPassword>
         </wrap:credentials>
         <wrap:extendedSettings>
            <xsd:responseFormat>JSON</xsd:responseFormat>
         </wrap:extendedSettings>
         <wrap:declareSection></wrap:declareSection>
         <wrap:sqlSelect>SELECT DISTINCT slice,ccti_category FROM VIC_CATEGORIZATION</wrap:sqlSelect>
         <wrap:orderByClause></wrap:orderByClause>
      </wrap:getSQLQueryResults>
   </soapenv:Body>
</soapenv:Envelope>``

I don´t know how.

Regards

**Comment by rashmihunt** [comment]
@fdabrao Please take a look at README which has example code to invoke a WebService using client APIs and how to formulate your JSON input argument as per your WSDL which becomes the payload/body shown in your soap envelope. https://github.com/strongloop/strong-soap#client 
Also, you can refer to examples under /examples directory for e.g https://github.com/strongloop/strong-soap/blob/master/example/stockquote.js and tests under https://github.com/strongloop/strong-soap/tree/master/test

**Comment by rashmihunt** [comment]
@fdabrao Hope above doc/examples/tests helped to answer your question.  We would be closing this issue as per information provided.

**Comment by fdabrao** [comment]
Ok, thanks for your help, yes, close it please.
