### ISSUE TITLE
strong-soap Client works with WSDL but others don't

### ISSUE THREAD

**Issue by kay-is** [strongloop/strong-soap#88]
I did a simple service with this library and tested it with the client, which worked. But trying this with the SOAPClient from PHP didn't. Somehow the types of my method are all UNKNOWN.

Maybe I have some error in my WSDL and the strong-soap client doesn't care as much as the PHP one.

```
<?xml version="1.0"?>
<definitions 
  name="MyData"
  targetNamespace="http://example.com/dataservice.wsdl"
  xmlns:this="http://example.com/dataservice.wsdl"
  xmlns:type="http://example.com/dataservice.xsd"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns="http://schemas.xmlsoap.org/wsdl/">

  <types>
    <schema
      targetNamespace="http://example.com/dataservice.xsd"
      xmlns="http://www.w3.org/2000/10/XMLSchema">

      <element name="dataPosition">
        <complexType>
          <all>
            <element name="serialNo" type="string"/>
            <element name="dataDate" type="string"/>
            <element name="dataTime" type="string"/>
            <element name="driveNo" type="string"/>
            <element name="driveStatus" type="string"/>
          </all>
        </complexType>
      </element>

      <element name="Result">
        <complexType>
          <all>
            <element name="code" type="int"/>
            <element name="msg" type="string"/>
          </all>
        </complexType>
      </element>

    </schema>
  </types>

  <message name="sendPositionInput">
    <part name="body" element="type:dataPosition"/>
  </message>

  <message name="sendPositionOutput">
    <part name="body" element="type:Result"/>
  </message>

  <portType name="dataPortType">
    <operation name="sendPosition">
      <input message="this:sendPositionInput"/>
      <output message="this:sendPositionOutput"/>
    </operation>
  </portType>

  <binding name="dataBinding" type="this:dataPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="sendPosition">
      <soap:operation soapAction="%SERVICE_LOCATION%/sendPosition"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="MyDataService">
    <port name="dataPort" binding="this:dataBinding">
      <soap:address location="%SERVICE_LOCATION%"/>
    </port>
  </service>

</definitions>
```

Maybe the vaildator is missing something?

**Comment by kay-is** [comment]
Found the error.

Somehow my XML schema version was wrong. Oxygen XML editor told me.

Doesn't work:

    <schema
      targetNamespace="http://example.com/dataservice.xsd"
      xmlns="http://www.w3.org/2000/10/XMLSchema">

Does work:

    <schema
      targetNamespace="http://example.com/dataservice.xsd"
      xmlns="http://www.w3.org/2001/XMLSchema">

Maybe the your validator could check for this too?

**Comment by rashmihunt** [comment]
@kay-is  strong-soap supports both http://www.w3.org/2000/10/XMLSchema and http://www.w3.org/2001/XMLSchema  and there are tests which uses http://www.w3.org/2000/10/XMLSchema under tests/wsdl directory. Also WSDL 1.1 https://www.w3.org/TR/wsdl has examples which uses http://www.w3.org/2000/10/XMLSchema  At this point, we are not planning to remove support for http://www.w3.org/2000/10/XMLSchema by adding validation to eliminate "http://www.w3.org/2000/10/XMLSchema" WSDLs. We will be closing this issue, working as expected.
