### ISSUE TITLE
substitutionGroup Handling?

### ISSUE THREAD

**Issue by Ebsy** [strongloop/strong-soap#89]
I've come across a problem with strong-soap that I suspect is related to the handling of substitutionGroup in the XSD.

The XSD references an element that is a substitutionGroup of the main element in that particular XSD. When I try to reference it as part of an object, there is no namespace prefix applied. However, when I reference the original, non-substitute element, the correct prefix is applied. I had a quick look at this repo's code and it appears that something is not working correctly?

src/parser/xsd/element.js
```
  postProcess(defintions) {
    var schemas = defintions.schemas;
    if (this.$ref) {
      this.ref = this.resolveSchemaObject(schemas, 'element', this.$ref);
    } else if (this.$type) {
      this.type = this.resolveSchemaObject(schemas, 'type', this.$type);
    }
    **if (this.substitutionGroup) {
      this.substitutionGroup = this.resolveSchemaObject(
        schemas, 'element', this.$substitutionGroup);
    }**
  } 
```

Shouldn't that be this.**$**substitutionGroup ? and after the property is applied, what does strong-soap do with it?

**Comment by rashmihunt** [comment]
@Ebsy Can you please send your failing test case along with your WSDL so that we can reproduce? In addition, you could also implement the fix, add a mocha test and submit a PR. Thank you!
