### ISSUE TITLE
How do I change the prefix?

### ISSUE THREAD

**Issue by magician11** [strongloop/strong-soap#90]
Specifically does anyone know how I change the namespace from `<soap:Header>` to `<soapenv:Header>` and similarly attributes to something like `soapenv:mustUnderstand="1"` ?

My code currently looks something like this:

    const soap = require('soap');
    const url = 'https://staging.identitymanagement.lexisnexis.com/identity-proofing/services/identityProofingServiceWS/v2?wsdl';
    
    soap.createClient(url, function(err, client) {
      if(err) {
        console.log('Error', err);
      }
      client.setSecurity(new soap.WSSecurity('username', 'password', { 'mustUnderstand': 1}));
      client.invokeIdentityService({ 'workFlow': 'SOME_FLOW' }, (err, result, raw, soapHeader) => {
        console.log('Error======================');
        console.log(err);
        console.log('Result=============================');
        console.log(result);
        console.log('raw==============================');
        console.log(raw);
        console.log('soapHeader', soapHeader);
      });
    });

It produces XML that looks something like this...

    <?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://cxf.apache.org/bindings/xformat" xmlns:tns="http://ws.identityproofing.idm.risk.lexisnexis.com/" xmlns:survey="http://ns.lexisnexis.com/survey/1.0" xmlns:identity="http://ns.lexisnexis.com/identity-proofing/1.0" xmlns:ns0="http://ns.lexisnexis.com/identity-proofing/1.0">
    <soap:Header>
        <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" soap:mustUnderstand="1">
        <wsu:Timestamp wsu:Id="Timestamp-2017-03-04T01:58:02Z">
            <wsu:Created>2017-03-04T01:58:02Z</wsu:Created>
            <wsu:Expires>2017-03-04T02:08:02Z</wsu:Expires>
        </wsu:Timestamp>
        <wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="SecurityToken-2017-03-04T01:58:02Z">
        <wsse:Username>username</wsse:Username>
        <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">password</wsse:Password>
        <wsu:Created>2017-03-04T01:58:02Z</wsu:Created>
    </wsse:UsernameToken>
    </wsse:Security>
    </soap:Header>
    <soap:Body>
        <tns:invokeIdentityService xmlns:ns2="http://tempuri.org/" xmlns:ns3="http://sillypets.com/xsd">
        <workFlow>SOME_FLOW</workFlow>
    </tns:invokeIdentityService>
    </soap:Body>
    </soap:Envelope>

Thanks!

**Comment by Ebsy** [comment]
Have you tried overrideRootElement in wsdlOptions? 
example here - https://github.com/strongloop/strong-soap/blob/master/test/request-response-samples/addPets__force_namespaces/wsdl_options.json

**Comment by magician11** [comment]
I did.. but it does't seem to change the XML.

My code..

```
const soap = require('strong-soap').soap; // https://github.com/strongloop/strong-soap
const url = 'https://staging.identitymanagement.lexisnexis.com/identity-proofing/services/identityProofingServiceWS/v2?wsdl';

const wsdlOptions = {
  "overrideRootElement": {
    "namespace": "testing",
    "xmlnsAttributes": [{
      "name": "xmlns:ns2",
      "value": "http://tempuri.org/"
    }, {
      "name": "xmlns:ns3",
      "value": "http://sillypets.com/xsd"
    }]
  }
}

soap.createClient(url, wsdlOptions, function(err, client) {
  if(err) {
    console.log('Error', err);
  }
  client.setSecurity(new soap.WSSecurity('username', 'password', { 'mustUnderstand': 1}));
  client.invokeIdentityService({ 'workFlow': 'WHITE_LABEL_VERIF_21_FLOW' }, (err, result, raw, soapHeader) => {
    console.log('Error======================');
    console.log(err);
  });
});

```

Doesn't seem to change the XML for the body value of the err object. i.e. It looks the same as above. I was expecting to see the word "testing" somewhere in the XML to see I was making a change.

**Comment by danofsteele** [comment]
I have the same problem, `overrideRootElement` has no effect. Any updates?

**Comment by magician11** [comment]
I ended up dropping this module when I realised I could just hardcode an XML fragment as a string to create exactly what I wanted, use string interpolation to insert my variables, and then use something like [request-promise-native](https://github.com/request/request-promise-native) to do a POST request.

```
  const { firstName, lastName, year, month, day, addressLine1, city, stateCode, zip } = req.body;

  const xmlReqBody = `
  <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://ws.identityproofing.idm.risk.lexisnexis.com/" xmlns:ns="http://ns.lexisnexis.com/identity-proofing/1.0" xmlns:ns1="http://ns.lexisnexis.com/survey/1.0">
  <soapenv:Header>
    <wsse:Security soapenv:mustUnderstand="1" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
    <wsse:UsernameToken wsu:Id="UsernameToken-49" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
    <wsse:Username>someusername</wsse:Username>
    <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">somepassword</wsse:Password>
  </wsse:UsernameToken>
</wsse:Security>
</soapenv:Header>
<soapenv:Body>
  <ws:invokeIdentityService>
    <identityProofingRequest ns:customerReference="TESTING" ns:locale="en_US" ns:transactionID="${new Date().toString()}" ns:version="2" xmlns="http://ns.lexisnexis.com/identity-proofing/1.0" xmlns:ns2="http://ns.lexisnexis.com/identity-proofing/1.0">
    <ns:workFlow>someworkflow</ns:workFlow>
    <ns:inputSubject>
      <ns:person>
        <ns:name>
          <ns:first>${firstName}</ns:first>
          <ns:last>${lastName}</ns:last>
        </ns:name>
        <ns:dateOfBirth>
          <ns:Year>${year}</ns:Year>
          <ns:Month>${month}</ns:Month>
          <ns:Day>${day}</ns:Day>
        </ns:dateOfBirth>
        <ns:address ns:addressPurpose="PRIMARY_RESIDENCE">
          <ns:addressLine1>${addressLine1}</ns:addressLine1>
          <ns:city>${city}</ns:city>
          <ns:stateCode>${stateCode}</ns:stateCode>
          <ns:zip5>${zip}</ns:zip5>
        </ns:address>
      </ns:person>
    </ns:inputSubject>
  </identityProofingRequest>
</ws:invokeIdentityService>
</soapenv:Body>
</soapenv:Envelope>`;

const options = {
  method: 'POST',
  uri: 'https://someurl.com/v2?wsdl',
  body: xmlReqBody,
};

rpn(options)
.then(response => console.log(response))
```

**Comment by danofsteele** [comment]
Thanks, although that's what I was afraid you were going to say.

**Comment by magician11** [comment]
@danofsteele it's actually a pretty ok solution for me. Even though the code is not as terse anymore, it's extremely clear what XML I'll be sending. And since this particular client of mine requires specific tweaks in the XML, this is much easier than trying to figure out how to get a module to render the same XML.

**Comment by derouck** [comment]
@danofsteele @magician11 Facing the same problem as well: you can do it by setting envelopeKey. But that mustUnderstand tag will not be affected so it breaks the xml if you use the security with mustUnderstand.

```
const options = {
    "envelopeKey": "soapenv"
}

```


It seems wsdlOptions should actually be inside this options object. Something like this:

```
const options = {
    wsdl_options: {
        overrideRootElement: ...
   }
}
```

**Comment by derouck** [comment]
I lost a lot of time trying to get it working with these node soap packages. They do some useful stuff, but in the end it's quite complicated to get the requests send, especially because I needed a different way of using WS-Security with certificates. There is support for it in this package, but [this ws.js package](https://github.com/yaronn/ws.js) handles it in a much cleaner way. It's probably interesting to have a look at integrating this for the WS-Security part. 

You end writing your xml yourself, but the security stuff is quite easy this way.

**Comment by danofsteele** [comment]
Thanks @derouck, I ended up doing the similar with a combination of `request` and `handlebars` to make the request and build the XML. There's a section in request's Readme about certificates that I was able to use; https://github.com/request/request#tlsssl-protocol

I made use of `soap.WSDL.open` to help build the request params and the`soap.XMLHandler` to parse the response XML.
