### ISSUE TITLE
.describe() returns {} object in AWS Lambda

### ISSUE THREAD

**Issue by grandeconcarne** [strongloop/strong-soap#91]
`var soap = require('strong-soap').soap;

soap.createClient('https://ws.campaigner.com/2013/01/contactmanagement.asmx?WSDL', 
    function(err, client) {
        console.log(client.describe());
    });`
Running the above using a local node 4.3.2 returns a populated service object. Running the above an AWS Lambda function returns and empty object. Any ideas / suggestions to solve?

**Comment by rashmihunt** [comment]
@grandeconcarne can install latest version of strong-soap from npm which is version 1.2.2 and test your usecase? https://www.npmjs.com/package/strong-soap

**Comment by grandeconcarne** [comment]
Thank you! That did it.

**Comment by rashmihunt** [comment]
Closing since issue is resolved for the originator.
