### ISSUE TITLE
Escaping back slash

### ISSUE THREAD

**Issue by dipakchandranp** [strongloop/strong-soap#95]
I was trying to access the SOAP service, and following were the code tried:

```
    var wsdlURL             = './payments/XiPayWS3x.wsdl';
    var options = {
        wsdl_headers :{
            user : 'domain\\user_name',
            password : xipay_password
        },
        endpoint: xipay_serviceURL
    };
    soap.createClient(wsdlURL, options, function(err, client) {
        console.log(client.httpClient.options);
    });

```

You can see in the above code I have given my user name with **'\\' two slash**, actually in the user name only **one slash** is there, I was trying to escape here. But after **escaping** like this also when I print the **httpClientOptions** it shows **two slashes**. And when I tried with removing the one slash, in the **httpClientOptions** there is **no slash** at all.

Due to this reason when ever I try to access a **SOAP service** I am getting **401 Error**.

Thanks for the help.

**Comment by raymondfeng** [comment]
I think `'domain\\user_name'` is the right way to escape the slash. How did you print out `httpClientOptions`?

**Comment by dipakchandranp** [comment]
Hi @raymondfeng ,

soap.createClient(wsdlURL, options, function(err, client) {
        console.log(client.httpClient.options);
});

**Comment by dipakchandranp** [comment]
Also in the strong-soap package, in following file `strong-soap/src/soap.js` we have function `createClient(url, options, callback, endpoint)` and try to print the option in this file.

In here also the we are getting invalid value for the user name. Escaping of slash is not working in here also.

**Comment by rashmihunt** [comment]
@dipakchandranp I tried your usecase and I don't see this issue.  I correctly see 'domain\user_name' in soap.createClient(..).  In wsdl.open(..) function where it eventually constructs new HTTPClient, new HttpClient(options) and calls  httpClient.request(..) to make a http request to get the WSDL and I see here also your username is ''domain\user_name' as expected. 

I am running on Mac OS. Wondering if your issue is platform specific? On what platform are your running this?

**Comment by rashmihunt** [comment]
@dipakchandranp  I looked a bit further and looks like it's just issue with printing using console.log (..).  If you debug your code and put a breakpoint and check options in createClient(..) or in http.js at line 132 - self._request(options, ..) function, just before http request is made, you can see the  username is correctly set to ''domain\user_name'. This means your test case should be working.  If it's not working, please check 
1) if the username and password expected by the remote webservice for downloading that WSDL is correct
2) also check setting username/password in hTTP request header is the correct way your remote webservice is expecting for downloading that WSDL?

**Comment by rashmihunt** [comment]
@dipakchandranp Let us know if above pointers helped. Will be closing this issue as working as design.

**Comment by rashmihunt** [comment]
Closing - working as expected. See above details.
